-- -- seeds/initial_data.sql
-- -- This seed file inserts sample data into all tables for preview purposes.

-- -- Seed users
-- insert into public.users (name, surname)
-- select
--   (array['Alice','Bob','Carol','Dave','Eve','Frank','Grace','Heidi','Ivan','Judy','Ken','Laura','Mallory','Niaj','Olivia','Peggy','Quentin','Rupert','Sybil','Trent','Uma','Victor','Wendy','Xavier','Yvonne','Zack'])[floor(random()*26+1)],
--   (array['Smith','Johnson','Williams','Brown','Jones','Miller','Davis','Garcia','Rodriguez','Wilson','Martinez','Anderson','Taylor','Thomas','Hernandez','Moore','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis'])[floor(random()*26+1)]
-- from generate_series(1,200) as s(id);

-- -- Seed clubs
-- insert into public.clubs (name, description, active, league)
-- with combos as (
--   select n as base_name, l as league
--   from unnest(array['Chess','Hiking','Robotics','Book','Music','Art','Drama','Soccer','Basketball','Photography','Cooking','Dance','Coding','Science','Math','History','Language','Debate','Cycling','Swimming']) as n
--   cross join unnest(array['junior','senior','university']) as l
-- )
-- select
--   base_name || ' Club',
--   'A club for ' || lower(base_name),
--   random() < 0.8,
--   league::public.club_league
-- from combos
-- order by random()
-- limit 50;

-- -- Seed club managers (1-3 per club)
-- insert into public.club_managers (club_id, user_id)
-- select
--   c.id,
--   u.id
-- from public.clubs c
-- join lateral (
--   select id from public.users order by random() limit (floor(random()*3)+1)
-- ) u on true;

-- -- Seed memberships (1-3 per user)
-- insert into public.memberships (user_id, club_id, year, confirmed)
-- select
--   u.id,
--   (select id from public.clubs order by random() limit 1),
--   (2022 + floor(random()*4))::int,
--   random() < 0.7
-- from public.users u,
-- generate_series(1, (floor(random()*3)+1)::int) as m(i);

-- -- Seed awards (~30% of users)
-- insert into public.awards (user_id, award, level)
-- select
--   u.id,
--   (array['Champion','Runner-up','Participant','Winner','Leader','Contributor'])[floor(random()*6+1)],
--   floor(random()*4+1)
-- from public.users u
-- where random() < 0.3;

-- -- Seed supervisors (~20% of users)
-- insert into public.supervisors (user_id, name, surname, email)
-- select
--   u.id,
--   (array['Supervisor','Manager','Director','Coach','Advisor'])[floor(random()*5+1)],
--   (array['One','Two','Three','Four','Five','Six'])[floor(random()*6+1)],
--   lower((array['manager','supervisor','director','coach','advisor'])[floor(random()*5+1)] || u.id::text || '@example.com')
-- from public.users u
-- where random() < 0.2;

-- -- Seed messages (100 entries)
-- insert into public.messages (type, platform, content, link)
-- select
--   (array['text','header','toast','redirect'])[floor(random()*4+1)]::public.message_type,
--   (array['debrief','fastballot','barca'])[floor(random()*3+1)]::public.message_platform,
--   jsonb_build_object('message', 'Sample message ' || s.id),
--   case when random() < 0.5 then null else '/link/' || s.id end
-- from generate_series(1,100) as s(id);