insert into role_permissions (role, permission)
values
  -- Developer: All permissions
  ('developer', 'awards.write'),
  ('developer', 'clubs.read'),
  ('developer', 'clubs.write'),
  ('developer', 'club_managers.read'),
  ('developer', 'club_managers.write'),
  ('developer', 'details.read'),
  ('developer', 'details.write'),
  ('developer', 'memberships.read'),
  ('developer', 'memberships.write'),
  ('developer', 'users.write'),
  ('developer', 'messages.read'),
  ('developer', 'messages.write'),
  ('developer', 'invoices.read'),
  ('developer', 'invoices.write'),
  ('developer', 'payments.read'),
  ('developer', 'payments.write'),
  ('developer', 'supervisors.read'),
  ('developer', 'supervisors.write'),
  ('developer', 'events.read'),
  ('developer', 'events.write'),
  ('developer', 'motions.read'),
  ('developer', 'motions.write'),
  ('developer', 'teams.read'),
  ('developer', 'teams.write'),
  ('developer', 'results.read'),
  ('developer', 'results.write'),

  -- Admin: All permissions
  ('admin', 'awards.write'),
  ('admin', 'clubs.read'),
  ('admin', 'clubs.write'),
  ('admin', 'club_managers.read'),
  ('admin', 'club_managers.write'),
  ('admin', 'details.read'),
  ('admin', 'details.write'),
  ('admin', 'memberships.read'),
  ('admin', 'memberships.write'),
  ('admin', 'users.write'),
  ('admin', 'messages.read'),
  ('admin', 'messages.write'),
  ('admin', 'invoices.read'),
  ('admin', 'invoices.write'),
  ('admin', 'payments.read'),
  ('admin', 'payments.write'),
  ('admin', 'supervisors.read'),
  ('admin', 'supervisors.write'),
  ('admin', 'events.read'),
  ('admin', 'events.write'),
  ('admin', 'motions.read'),
  ('admin', 'motions.write'),
  ('admin', 'teams.read'),
  ('admin', 'teams.write'),
  ('admin', 'results.read'),
  ('admin', 'results.write'),

  -- Cap: Specific read/write permissions
  ('cap', 'awards.write'),
  ('cap', 'details.read'),
  ('cap', 'memberships.read'),
  ('cap', 'messages.read'),
  ('cap', 'messages.write'),
  ('cap', 'events.read'),
  ('cap', 'events.write'),
  ('cap', 'motions.read'),
  ('cap', 'motions.write'),
  ('cap', 'teams.read'),
  ('cap', 'teams.write'),
  ('cap', 'results.read'),
  ('cap', 'results.write'),


  -- Junior Organizer: Specific read permissions
  ('junior_organizer', 'details.read'),
  ('junior_organizer', 'memberships.read'),
  ('junior_organizer', 'events.read'),
  ('junior_organizer', 'events.write'),
  ('junior_organizer', 'teams.read'),
  ('junior_organizer', 'teams.write'),

  -- Senior Organizer: Specific read permissions
  ('senior_organizer', 'details.read'),
  ('senior_organizer', 'memberships.read'),
  ('senior_organizer', 'events.read'),
  ('senior_organizer', 'events.write'),
  ('senior_organizer', 'motions.read'),
  ('senior_organizer', 'teams.read'),
  ('senior_organizer', 'teams.write'),
  ('senior_organizer', 'results.read'),

  -- Motions Committee Member: Specific read/write permissions
  ('mc_member', 'events.read'),
  ('mc_member', 'events.write'),
  ('mc_member', 'motions.read'),
  ('mc_member', 'motions.write')