-- Enumeration for club leagues
create type public.club_league as enum (
  'junior',
  'senior',
  'university'
);

create table "clubs" (
  "id" bigint generated by default as identity primary key,
  "created_at" timestamptz not null default now(),
  "name" text not null,
  "description" text,
  "active" boolean not null default true,
  "league" club_league not null default 'senior'::club_league,
  unique ("name", "league")
);
comment on table "clubs" is 'Stores information about clubs.';

create table "club_managers" (
  "id" bigint generated by default as identity primary key,
  "created_at" timestamptz not null default now(),
  "club_id" bigint not null references "clubs" ("id") on delete cascade,
  "user_id" bigint not null references "users" ("id") on delete cascade,
  unique ("club_id", "user_id")
);
comment on table "club_managers" is 'Stores relationships between users and the clubs they manage.';

create index ix_club_managers_club_id on public.club_managers (club_id);
create index ix_club_managers_user_id on public.club_managers (user_id);

create table "memberships" (
  "id"          bigint generated by default as identity primary key,
  "created_at"  timestamptz not null default now(),
  "user_id"     bigint not null references "users" ("id"),
  "club_id"     bigint not null references "clubs" ("id"),
  "year"        smallint not null,
  unique ("user_id", "club_id", "year")
);
comment on table "memberships" is 'Table for storing user memberships in clubs.';

create index ix_memberships_club_id on public.memberships (club_id);
create index ix_memberships_user_id on public.memberships (user_id);

-- Allows any authenticated user to read data for clubs that are marked as active.
create policy "Allow authenticated users to read active clubs" on "clubs" for select to authenticated using (active = true);

-- Allows users who are managers of a specific club to update that club's data.
create policy "Allow club managers to update their clubs" on "clubs" for update to authenticated using (exists (select 1 from "club_managers" where "club_managers"."club_id" = "clubs".id and "club_managers"."user_id" = (select id from public.users where auth_id = (select auth.uid()))));

-- Role-based policies for "clubs" table.
-- Allows users with the 'clubs.read' permission to read club data.
create policy "Allow users with clubs.read to read clubs" on "clubs" for select to authenticated using (authorize('clubs.read'));
-- Allows users with the 'clubs.write' permission to create new clubs.
create policy "Allow users with clubs.write to create clubs" on "clubs" for insert to authenticated with check (authorize('clubs.write'));
-- Allows users with the 'clubs.write' permission to update existing club data.
create policy "Allow users with clubs.write to update clubs" on "clubs" for update to authenticated using (authorize('clubs.write'));

alter table public.clubs enable row level security;

-- Allows authenticated users to read club manager information without restrictions.
create policy "Allow authenticated users to read club managers for active club" on "club_managers" for select to authenticated;

-- Role-based policies for "club_managers" table.
-- Allows users with the 'club_managers.read' permission to read club manager data.
create policy "Allow users with club_managers.read to read club managers" on "club_managers" for select to authenticated using (authorize('club_managers.read'));
-- Allows users with the 'club_managers.write' permission to create club manager assignments.
create policy "Allow users with club_managers.write to create club managers" on "club_managers" for insert to authenticated with check (authorize('club_managers.write'));
-- Allows users with the 'club_managers.write' permission to update club manager assignments.
create policy "Allow users with club_managers.write to update club managers" on "club_managers" for update to authenticated using (authorize('club_managers.write'));
-- Allows users with the 'club_managers.write' permission to delete club manager assignments.
create policy "Allow users with club_managers.write to delete club managers" on "club_managers" for delete to authenticated using (authorize('club_managers.write'));

alter table public.club_managers enable row level security;

-- Policies for "memberships" table
-- Allows users to create, read, and update their own club memberships. Deletion by the user is not permitted by this policy.
create policy "Allow users to read their own memberships" on public.memberships as permissive for select to authenticated using ((select auth.uid()) = (select auth_id from public.users where id = memberships.user_id));
create policy "Allow users to create their own memberships" on public.memberships as permissive for insert to authenticated with check ((select auth.uid()) = (select auth_id from public.users where id = memberships.user_id));
create policy "Allow users to update their own memberships" on public.memberships as permissive for update to authenticated using ((select auth.uid()) = (select auth_id from public.users where id = memberships.user_id)) with check ((select auth.uid()) = (select auth_id from public.users where id = memberships.user_id));
-- Allows all authenticated users to read a user's memberships if that user's profile is public.
create policy "Allow authenticated users to read public memberships" on public.memberships as permissive for select to authenticated using (exists (select 1 from public.users where id = memberships.user_id and public = true));
-- Policies for role-based access to memberships.
-- Allows users with the 'memberships.read' permission to read memberships.
create policy "Allow user roles to read memberships" on public.memberships as permissive for select to authenticated using (authorize('memberships.read'));
-- Allows users with the 'memberships.write' permission to update memberships.
create policy "Allow user roles to update memberships" on public.memberships as permissive for update to authenticated using (authorize('memberships.write')) with check (authorize('memberships.write'));

alter table public.memberships enable row level security;