-- ENUMERATION FOR EVENT TYPES
create type public.event_type as enum (
  'tournament',
  'seminar',
  'other'
);






-- ENUMERATION FOR EVENT STATUSES
create type public.event_status as enum (
  'ongoing',
  'completed',
  'cancelled'
);






-- TABLE FOR STORING EVENTS

create table "events" (
    "id" bigint generated by default as identity primary key,
    "code" text not null unique,
    "created_at" timestamptz not null default now(),
    "name" text not null,
    "type" public.event_type not null default 'other'::public.event_type,
    "status" public.event_status not null default 'ongoing'::public.event_status,
    "external" text default null,
    "draft" boolean not null default false,
    "data" jsonb not null default '{}'::jsonb,
    "registration_data" jsonb not null default '{}'::jsonb,
    "search_index" text generated always as (public.create_search(lower(name))) stored
);

comment on table "events" is 'Stores information about events.';

create index ix_events_code on public.events (code);
create index ix_events_status on public.events (status);
create index ix_events_draft on public.events (draft);
create index ix_events_search_index on public.events (search_index);





-- TABLE FOR STORING EVENT ORGANIZERS

create table "event_organizers" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "event_id" bigint not null references "events" ("id") on delete cascade,
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "contact_info" jsonb not null default '{}'::jsonb,
    unique ("event_id", "user_id")
);

comment on table "event_organizers" is 'Stores relationships between users and the events they organize.';

create index ix_event_organizers_event_id on public.event_organizers (event_id);
create index ix_event_organizers_user_id on public.event_organizers (user_id);





-- TABLE FOR STORING EVENT REGISTRATIONS

create table "event_registrations" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "event_id" bigint not null references "events" ("id") on delete cascade,
    "user_id" bigint references "users" ("id") on delete cascade,
    "role" text not null default 'participant',
    "data" jsonb not null default '{}'::jsonb,
    unique ("event_id", "user_id")
);

comment on table "event_registrations" is 'Stores user registrations for events.';

create index ix_event_registrations_event_id on public.event_registrations (event_id);
create index ix_event_registrations_user_id on public.event_registrations (user_id);





-- POLICIES FOR THE "events" TABLE

-- Allows authenticated users to read events which are not drafts, or users with 'events.read' permission to read any event.
create policy "Allow read access to events" on "events" for select to authenticated using (
    (draft = false)
    or authorize('events.read')
);

-- Allows users with 'events.write' permission to create new events.
create policy "Allow users with events.write to create events" on "events" for insert to authenticated with check (authorize('events.write'));

-- Allows users with 'events.write' permission to update existing events.
create policy "Allow users with events.write to update events" on "events" for update to authenticated using (
    authorize('events.write')
);

-- Enable row level security for the "events" table
alter table public.events enable row level security;





-- POLICIES FOR THE "event_organizers" TABLE

-- Allows authenticated users to read event organizers for events they can access, or users with 'events.read' permission to read any event organizer.
create policy "Allow read access to event organizers" on "event_organizers" for select to authenticated using (
    exists (
        select 1 from "events"
        where "events"."id" = "event_organizers"."event_id"
        and (draft = false or authorize('events.read'))
    )
    or authorize('events.read')
);

-- Allows users with 'events.write' permission to do anything with event organizers.
create policy "Allow users with events.write to manage event organizers" on "event_organizers" for all to authenticated using (authorize('events.write'));

-- Enable row level security for the "event_organizers" table
alter table public.event_organizers enable row level security;





-- POLICIES FOR THE "event_registrations" TABLE

-- Allow authenticated users to do anything with their own event registrations.
create policy "Allow users to manage their own event registrations" on "event_registrations" for all to authenticated using (
    ((select (auth.jwt()->>'user_id'))::bigint) = user_id
);

-- Allow users with 'events.read' permission to read any event registration.
create policy "Allow users with events.read to read event registrations" on "event_registrations" for select to authenticated using (authorize('events.read'));

-- Allow users with 'events.write' permission to do anything with event registrations.
create policy "Allow users with events.write to manage event registrations" on "event_registrations" for all to authenticated using (authorize('events.write'));

-- Enable row level security for the "event_registrations" table
alter table public.event_registrations enable row level security;