-- ENUMERATION FOR ROUND TYPES

create type public.round_type as enum (
  'preliminary',
  'elimination'
);





-- ENUMERATION FOR ROUND STATUSES

create type public.round_status as enum (
    'scheduled',
    'in_progress',
    'completed'
);





-- ENUMERATION FOR MOTION TYPES

create type public.motion_type as enum (
    'prepared',
    'impromptu'
);





-- ENUMERATION FOR TEAM TYPES

create type public.team_type as enum (
    'active',
    'archived'
);





-- ENUMERATION FOR ADJUDICATOR ROLES

create type public.adjudicator_role as enum (
    'adjudicator',
    'trainee',
    'chair'
);





-- ENUMERATION FOR SUPPLEMENT TYPES

create type public.supplement_type as enum (
    'cross',
    'reply'
);





-- TABLE FOR STORING MOTIONS

create table "motions" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "motion_type" public.motion_type not null default 'prepared'::public.motion_type,
    "motion_text" text not null,
    "event_id" bigint not null references "events" ("id") on delete cascade,
    "infoslide" text default null
);

comment on table "motions" is 'Stores information about debate motions.';





-- TABLE FOR STORING ROUNDS

create table "rounds" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "event_id" bigint not null references "events" ("id") on delete cascade,
    "motion_id" bigint references "motions" ("id") on delete set null,
    "name" text not null,
    "type" public.round_type not null default 'preliminary'::public.round_type,
    "status" public.round_status not null default 'scheduled'::public.round_status,
    unique ("event_id", "name")
);

comment on table "rounds" is 'Stores information about debate rounds.';
create index ix_rounds_event_id on public.rounds (event_id);
create index ix_rounds_motion_id on public.rounds (motion_id);





-- TABLE FOR STORING DEBATE TEAMS

create table "teams" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "name" text not null unique,
    "type" public.team_type not null default 'active'::public.team_type,
    "search_index" text generated always as (public.create_search(lower(name))) stored
);

comment on table "teams" is 'Stores information about debate teams.';

create index ix_teams_type on public.teams (type);
create index ix_teams_search_index on public.teams (search_index);





-- TABLE FOR STORING TEAM MEMBERSHIPS

create table "team_memberships" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "team_id" bigint not null references "teams" ("id") on delete cascade,
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "event_id" bigint not null references "events" ("id") on delete cascade,
    unique ("team_id", "user_id", "event_id")
);

comment on table "team_memberships" is 'Stores relationships between users and the teams they belong to.';
create index ix_team_memberships_team_id on public.team_memberships (team_id);
create index ix_team_memberships_user_id on public.team_memberships (user_id);
create index ix_team_memberships_event_id on public.team_memberships (event_id);





-- TABLE FOR STORING DEBATES

create table "debates" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "round_id" bigint not null references "rounds" ("id") on delete cascade,
    "room" text not null,
    unique ("round_id", "room")
);

comment on table "debates" is 'Stores information about debates within rounds used for tabbing and adjudication.';
create index ix_debates_round_id on public.debates (round_id);





-- TABLE FOR STORING ADJUDICATOR ASSIGNMENTS

create table "adjudicator_assignments" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "debate_id" bigint not null references "debates" ("id") on delete cascade,
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "role" public.adjudicator_role not null default 'adjudicator'::public.adjudicator_role,
    unique ("debate_id", "user_id")
);

comment on table "adjudicator_assignments" is 'Stores adjudicator assignments for debates.';
create index ix_adjudicator_assignments_debate_id on public.adjudicator_assignments (debate_id);
create index ix_adjudicator_assignments_user_id on public.adjudicator_assignments (user_id);





-- TABLE FOR STORING TEAM ASSIGNMENTS

create table "team_assignments" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "debate_id" bigint not null references "debates" ("id") on delete cascade,
    "team_id" bigint not null references "teams" ("id") on delete cascade,
    "side" text not null default 'affirmative',
    unique ("debate_id", "team_id")
);

comment on table "team_assignments" is 'Stores team assignments for debates.';
create index ix_team_assignments_debate_id on public.team_assignments (debate_id);
create index ix_team_assignments_team_id on public.team_assignments (team_id);





-- TABLE FOR STORING TEAM SCORES

create table "team_scores" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "team_id" bigint not null references "teams" ("id") on delete cascade,
    "debate_id" bigint not null references "debates" ("id") on delete cascade,
    "adjudicator_id" bigint not null references "users" ("id") on delete cascade default (current_setting('jwt.claims.user_id')::bigint),
    "adjudicator_role" public.adjudicator_role not null default 'adjudicator'::public.adjudicator_role,
    "rank" integer not null,
    unique ("debate_id", "team_id", "adjudicator_id")
);

comment on table "team_scores" is 'Stores scores and ranks for teams in debates.';
create index ix_team_scores_team_id on public.team_scores (team_id);
create index ix_team_scores_debate_id on public.team_scores (debate_id);
create index ix_team_scores_adjudicator_id on public.team_scores (adjudicator_id);





-- TABLE FOR STORING DEBATER SCORES

create table "debater_scores" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "team_score_id" bigint not null references "team_scores" ("id") on delete cascade,
    "position" integer not null,
    "score" integer not null,
    "categories" jsonb not null default '{}'::jsonb
);

comment on table "debater_scores" is 'Stores scores for individual debaters in debates.';
create index ix_debater_scores_user_id on public.debater_scores (user_id);
create index ix_debater_scores_team_score_id on public.debater_scores (team_score_id);





-- TABLE FOR STORING SUPPLEMENTARY SPEECHES

create table "supplementary_speeches" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "team_score_id" bigint not null references "team_scores" ("id") on delete cascade,
    "type" public.supplement_type not null default 'cross'::public.supplement_type,
    "score" integer not null,
    "categories" jsonb not null default '{}'::jsonb
);

comment on table "supplementary_speeches" is 'Stores supplementary speeches for teams in debates.';
create index ix_supplementary_speeches_team_score_id on public.supplementary_speeches (team_score_id);





-- POLICIES FOR THE "motions" TABLE

-- Allows authenticated users to read motions if the motion is prepared, or the round where the motion is used is not a scheduled round or the user has 'motions.read' permission.
create policy "Allow read access to motions" on "motions" for select to authenticated using (
    (
        motion_type = ' prepared'
        or exists (
            select 1
            from "rounds"
            where "rounds"."motion_id" = "motions"."id"
                and "rounds"."status" != 'scheduled'
        )
    )
    or authorize('motions.read')
);
-- Allows users with 'motions.write' permission to create new motions.
create policy "Allow users with motions.write to create motions" on "motions" for insert to authenticated with check (authorize('motions.write'));
-- Allows users with 'motions.write' permission to update existing motions.
create policy "Allow users with motions.write to update motions" on "motions" for update to authenticated using (authorize('motions.write'));

alter table public.motions enable row level security;





-- POLICIES FOR THE "rounds" TABLE

-- Allows authenticated users to read rounds if the round is not scheduled, or the user has 'events.read' permission.
create policy "Allow read access to rounds" on "rounds" for select to authenticated using (
    (status != 'scheduled' or authorize('events.read'))
    or authorize('events.read')
);
-- Allows users with 'events.write' permission to create new rounds.
create policy "Allow users with events.write to create rounds" on "rounds" for insert to authenticated with check (authorize('events.write'));
-- Allows users with 'events.write' permission to update existing rounds.
create policy "Allow users with events.write to update rounds" on "rounds" for update to authenticated using (authorize('events.write'));

alter table public.rounds enable row level security;





-- POLICIES FOR THE "teams" TABLE

-- Allows authenticated users to read any teams
create policy "Allow read access to teams" on "teams" for select to authenticated using (true);

-- Allows users with 'teams.write' permission to create new teams.
create policy "Allow users with teams.write to create teams" on "teams" for insert to authenticated with check (authorize('teams.write'));
-- Allows users with 'teams.write' permission to update existing teams.
create policy "Allow users with teams.write to update teams" on "teams" for update to authenticated using (authorize('teams.write'));

alter table public.teams enable row level security;





-- POLICIES FOR THE "team_memberships" TABLE

-- Allows authenticated users to read team memberships.
create policy "Allow read access to team memberships" on "team_memberships" for select to authenticated using (true);
-- Allows users with 'team_memberships.write' permission to do anything with team memberships.
create policy "Allow users with teams.write to manage team memberships" on "team_memberships" for all to authenticated using (authorize('teams.write'));

alter table public.team_memberships enable row level security;





-- POLICIES FOR THE "debates" TABLE

-- Allows authenticated users to read debates if the round is not scheduled, or the user has 'debates.read' permission.
create policy "Allow read access to debates" on "debates" for select to authenticated using (
    (exists (
        select 1 from "rounds"
        where "rounds"."id" = "debates"."round_id"
        and (rounds.status != 'scheduled')
    ) or authorize('results.read'))
);

-- Allows users with 'results.write' to do anything with debates.
create policy "Allow users with results.write to manage debates" on "debates" for all to authenticated using (authorize('results.write'));

alter table public.debates enable row level security;





-- POLICIES FOR THE "adjudicator_assignments" TABLE

-- Allows authenticated users to read adjudicator assignments if the debate is not scheduled, or the user has 'results.read' permission.
create policy "Allow read access to adjudicator assignments" on "adjudicator_assignments" for select to authenticated using (
    (exists (
        select 1 from "debates"
        where "debates"."id" = "adjudicator_assignments"."debate_id"
        and debates.round_id in (
            select id from "rounds" where status != 'scheduled'
        )
    ) or authorize('results.read'))
);

-- Allows users with 'results.write' to do anything with adjudicator assignments.
create policy "Allow users with results.write to manage adjudicator assignments" on "adjudicator_assignments" for all to authenticated using (authorize('results.write'));

alter table public.adjudicator_assignments enable row level security;





-- POLICIES FOR THE "team_assignments" TABLE

-- Allows authenticated users to read team assignments if the debate is not scheduled, or the user has 'results.read' permission.
create policy "Allow read access to team assignments" on "team_assignments" for select to authenticated using (
    (exists (
        select 1 from "debates"
        where "debates"."id" = "team_assignments"."debate_id"
        and debates.round_id in (
            select id from "rounds" where status != 'scheduled'
        )
    ) or authorize('results.read'))
);

-- Allows users with 'results.write' to do anything with team assignments.
create policy "Allow users with results.write to manage team assignments" on "team_assignments" for all to authenticated using (authorize('results.write'));

alter table public.team_assignments enable row level security;





-- POLICIES FOR THE "team_scores" TABLE

-- Allows authenticated users to read team scores if the event is completed, or the user has 'results.read' permission.
create policy "Allow read access to team scores" on "team_scores" for select to authenticated using (
    (
        exists (
            select 1
            from "debates" d
            join "rounds" r on r.id = d.round_id
            join "events" e on e.id = r.event_id
            where d.id = "team_scores".debate_id
                and e.status = 'completed'
        )
        or authorize('results.read')
    )
);

-- Allows authenticated users to do anything with the team scores if they are the adjudicator or have 'results.write' permission.
create policy "Allow users to manage their own team scores" on "team_scores" for all to authenticated using (
    ((select (auth.jwt()->>'user_id'))::bigint) = adjudicator_id
    or authorize('results.write')
);

alter table public.team_scores enable row level security;





-- POLICIES FOR THE "debater_scores" TABLE

-- Allows authenticated users to read debater scores if the event is completed, or the user has 'results.read' permission.
create policy "Allow read access to debater scores" on "debater_scores" for select to authenticated using (
    (
        exists (
            select 1
            from "team_scores" ts
            join "debates" d on d.id = ts.debate_id
            join "rounds" r on r.id = d.round_id
            join "events" e on e.id = r.event_id
            where ts.id = "debater_scores".team_score_id
                and e.status = 'completed'
        )
        or authorize('results.read')
    )
);

-- Allows authenticated users to do anything with the debater scores if they are the adjudicator of the team_score or have 'results.write' permission.
create policy "Allow users to manage their own debater scores" on "debater_scores" for all to authenticated using (
    ((select (auth.jwt()->>'user_id'))::bigint) = (select team_scores.adjudicator_id from team_scores where team_scores.id = debater_scores.team_score_id)
    or authorize('results.write')
);

alter table public.debater_scores enable row level security;





-- POLICIES FOR THE "supplementary_speeches" TABLE

-- Allows authenticated users to read supplementary speeches if the event is completed, or the user has 'results.read' permission.
create policy "Allow read access to supplementary speeches" on "supplementary_speeches" for select to authenticated using (
    (
        exists (
            select 1
            from "team_scores" ts
            join "debates" d on d.id = ts.debate_id
            join "rounds" r on r.id = d.round_id
            join "events" e on e.id = r.event_id
            where ts.id = "supplementary_speeches".team_score_id
                and e.status = 'completed'
        )
        or authorize('results.read')
    )
);

-- Allows authenticated users to do anything with the supplementary speeches if they are the adjudicator of the team_score or have 'results.write' permission.
create policy "Allow users to manage their own supplementary speeches" on "supplementary_speeches" for all to authenticated using (
    ((select (auth.jwt()->>'user_id'))::bigint) = (select team_scores.adjudicator_id from team_scores where team_scores.id = supplementary_speeches.team_score_id)
    or authorize('results.write')
);

alter table public.supplementary_speeches enable row level security;