-- Enumerations and table for platform messages
create type public.message_type as enum (
  'text',
  'header',
  'toast',
  'redirect'
);

create type public.message_platform as enum (
  'debrief',
  'fastballot',
  'barca'
);

create table "messages" (
  "id" bigint generated by default as identity primary key,
  "created_at" timestamptz not null default now(),
  "type" public.message_type not null default 'text'::public.message_type,
  "platform" public.message_platform not null default 'debrief'::public.message_platform,
  "content" jsonb not null,
  "link" text default null
);
comment on table "messages" is 'Platform messages that can be sent to users.';

create index ix_messages_platform on public.messages (platform);
create index ix_messages_type on public.messages (type);

-- Allow all authenticated users to read messages.
create policy "Allow authenticated users to read messages" on "messages" for select to authenticated using (true);

-- Allow users with the 'messages.write' permission to create new messages.
create policy "Allow users with messages.write to create messages" on "messages" for insert to authenticated with check (authorize('messages.write'));
-- Allow users with the 'messages.write' permission to update existing messages.
create policy "Allow users with messages.write to update messages" on "messages" for update to authenticated using (authorize('messages.write'));
-- Allow users with the 'messages.write' permission to delete messages.
create policy "Allow users with messages.write to delete messages" on "messages" for delete to authenticated using (authorize('messages.write'));

alter table public.messages enable row level security;