-- Enumeration for payment status
create type public.payment_status as enum ('pending', 'completed', 'failed');

create table "invoices" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "amount" numeric(10,2) not null,
    "status" payment_status not null default 'pending'::payment_status
);

create table "payment_items" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "user_id" bigint not null unique references "users" ("id") on delete cascade,
    "amount" numeric(10,2) not null,
    "comment" text default null,
    "status" payment_status not null default 'pending'::payment_status,
    "invoice_id" bigint references "invoices" ("id") on delete set null,
    "membership_id" bigint references "memberships" ("id") on delete set null
);
comment on table "payment_items" is 'Stores payment item information for users.';

create index ix_payment_items_user_id on public.payment_items (user_id);
create index ix_payment_items_status on public.payment_items (status);
create index ix_payment_items_invoice_id on public.payment_items (invoice_id);
create index ix_payment_items_membership_id on public.payment_items (membership_id);
create index ix_payment_items_created_at on public.payment_items (created_at);

-- Policies for the "invoices" table
-- Allows any authenticated user to read their own invoice data.
create policy "Allow authenticated users to read their own invoices" on "invoices" for select to authenticated using (auth.uid() = (select auth_id from public.users where id = user_id));
-- Allow users with the 'invoices.write' permission to update existing invoice data.
create policy "Allow users with invoices.write to update invoices" on "invoices" for update to authenticated using (authorize('invoices.write'));
-- Allow users with the 'invoices.read' permission to read invoice data.
create policy "Allow users with invoices.read to read invoices" on "invoices" for select to authenticated using (authorize('invoices.read'));

alter table public.invoices enable row level security;

create index ix_invoices_user_id on public.invoices (user_id);
create index ix_invoices_status on public.invoices (status);

-- Policies for the "payment_items" table
-- Allows any authenticated user to read their own payment item data.
create policy "Allow authenticated users to read their own payment_items" on "payment_items" for select to authenticated using (auth.uid() = (select auth_id from public.users where id = user_id));

-- Allow users with the 'payment_items.write' permission to create new payment_items.
create policy "Allow users with payment_items.write to create payment_items" on "payment_items" for insert to authenticated with check (authorize('payment_items.write'));
-- Allow users with the 'payment_items.write' permission to update existing payment item data.
create policy "Allow users with payment_items.write to update payment_items" on "payment_items" for update to authenticated using (authorize('payment_items.write'));
-- Allow users with the 'payment_items.read' permission to read payment item data.
create policy "Allow users with payment_items.read to read payment_items" on "payment_items" for select to authenticated using (authorize('payment_items.read'));
-- Allow users with the 'payment_items.write' permission to delete payment item data.
create policy "Allow users with payment_items.delete to delete payment_items" on "payment_items" for delete to authenticated using (authorize('payment_items.write'));

alter table public.payment_items enable row level security;

-- Create function to update the status of payment items based on invoice status
create or replace function update_payment_item_status()
returns trigger as $$
begin
    if new.status = 'completed' then
        update payment_items set status = 'completed' where invoice_id = new.id;
    elsif new.status = 'failed' then
        update payment_items set status = 'failed' where invoice_id = new.id;
    end if;
    return new;
end;
$$ language plpgsql;

create trigger trg_update_payment_item_status
after update on invoices
for each row
execute procedure update_payment_item_status();
