-- Enumeration for payment status
create type public.payment_status as enum ('pending', 'completed', 'failed');

create table "invoices" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "user_id" bigint not null references "users" ("id") on delete cascade,
    "amount" numeric(10,2) not null,
    "status" payment_status not null default 'pending'::payment_status
);

comment on table "invoices" is 'Stores invoice information for users.';

create table "payments" (
    "id" bigint generated by default as identity primary key,
    "created_at" timestamptz not null default now(),
    "user_id" bigint not null unique references "users" ("id") on delete cascade,
    "amount" numeric(10,2) not null,
    "comment" text default null,
    "invoice_id" bigint references "invoices" ("id") on delete set null
);

comment on table "payments" is 'Stores payment information for users.';

create index ix_payments_user_id on public.payments (user_id);
create index ix_payments_invoice_id on public.payments (invoice_id);
create index ix_payments_created_at on public.payments (created_at);

-- Policies for the "invoices" table
-- Allows authenticated users to read their own invoices, or users with 'invoices.read' to read any invoice.
create policy "Allow read access to invoices" on "invoices" for select to authenticated using (
  ((select (auth.jwt()->>'user_id'))::bigint) = user_id
  or authorize('invoices.read')
);
-- Allow users with the 'invoices.write' permission to update existing invoice data.
create policy "Allow users with invoices.write to update invoices" on "invoices" for update to authenticated using (authorize('invoices.write'));

alter table public.invoices enable row level security;

create index ix_invoices_user_id on public.invoices (user_id);
create index ix_invoices_status on public.invoices (status);

-- Policies for the "payments" table
-- Allows authenticated users to read their own payments, or users with 'payments.read' to read any payment.
create policy "Allow read access to payments" on "payments" for select to authenticated using (
  ((select (auth.jwt()->>'user_id'))::bigint) = user_id
  or authorize('payments.read')
);

-- Allow users with the 'payments.write' permission to create new payments.
create policy "Allow users with payments.write to create payments" on "payments" for insert to authenticated with check (authorize('payments.write'));
-- Allow users with the 'payments.write' permission to update existing payment item data.
create policy "Allow users with payments.write to update payments" on "payments" for update to authenticated using (authorize('payments.write'));
-- Allow users with the 'payments.read' permission to read payment item data.
create policy "Allow users with payments.read to read payments" on "payments" for select to authenticated using (authorize('payments.read'));
-- Allow users with the 'payments.write' permission to delete payment item data.
create policy "Allow users with payments.delete to delete payments" on "payments" for delete to authenticated using (authorize('payments.write'));

alter table public.payments enable row level security;
