create extension unaccent;

create function public.create_search(text)  
returns text as
$$
  set search_path = '';
  select regexp_replace(unaccent($1), '[^a-zA-Z0-9]', '', 'g')
$$ language sql IMMUTABLE;

create type public.app_role as enum (
  'developer',
  'admin',
  'cap',
  'junior_organizer',
  'senior_organizer',
  'mc_member',
  'user'
);

create type public.app_permission as enum (
  'awards.write',
  'clubs.read',
  'clubs.write',
  'club_managers.read',
  'club_managers.write',
  'details.read',
  'details.write',
  'memberships.read',
  'memberships.write',
  'users.write',
  'messages.read',
  'messages.write',
  'invoices.read',
  'invoices.write',
  'payments.read',
  'payments.write',
  'supervisors.read',
  'supervisors.write'
);

create table "users" (
  "id"          bigint generated by default as identity primary key,
  "created_at"  timestamptz not null default now(),
  "auth_id"     uuid default auth.uid() unique references "auth"."users" ("id"),
  "name"        text not null,
  "surname"     text not null,
  "search_index" text generated always as (public.create_search(lower(name || surname))) stored
);
comment on table "users" is 'Table for storing basic user information.';

create index ix_users_auth_id on public.users (auth_id);
-- Removed invalid index creation: create index ix_users_public on public.users (public);
create index ix_users_search_index on public.users (search_index);

create table "awards" (
  "id"          bigint generated by default as identity primary key,
  "created_at"  timestamptz not null default now(),
  "awarded_by"  bigint references "users" ("id") on delete set null default (current_setting('jwt.claims.user_id')::bigint),
  "user_id"     bigint not null references "users" ("id") on delete cascade,
  "award"       text not null,
  "level"       smallint not null,
  unique ("user_id", "award", "level")
);
comment on table "awards" is 'Table for storing awards given to users.';

create index ix_awards_user_id on public.awards (user_id);

create table "claims" (
  "id"          bigint generated by default as identity primary key,
  "user_id"     bigint not null unique references "users" ("id") on delete cascade,
  "role"        app_role not null default 'user'::app_role,
  "credential"  smallint not null default 0,
  "additional"  jsonb not null default '{}'::jsonb
);
comment on table "claims" is 'Table for storing user claims, such as roles and credentials.';

create index ix_claims_role on public.claims (role);

create table "role_permissions" (
  "id"          bigint generated by default as identity primary key,
  "role"        app_role not null,
  "permission"  app_permission not null,
  unique ("role", "permission")
);
comment on table public.role_permissions is 'Maps application roles to their granted permissions.';

create table "details" (
  "id"          bigint generated by default as identity primary key,
  "user_id"     bigint not null unique references "users" ("id") on delete cascade,
  "birthdate"   date,
  "address"     text,
  "email"       text,
  "phone"       text,
  "socials"     text[] default '{}'::text[]
);
comment on table "details" is 'Table for storing additional user details that are always private.';

create table "supervisors" (
  "id"          bigint generated by default as identity primary key,
  "created_at"  timestamptz not null default now(),
  "user_id"     bigint not null unique references "users" ("id") on delete cascade,
  "name"        text not null,
  "surname"     text not null,
  "email"       text not null
);

-- Trigger function to automatically create related records in 'claims' and 'details' when a new user is created.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.claims (user_id, role, credential)
  values (new.id, 'user', 0);
  insert into public.details (user_id)
  values (new.id);
  return new;
end;
$$;

create function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable security definer set search_path = ''
as $$
declare
  claims jsonb;
  user_role public.app_role;
  user_credential smallint;
  user_additional jsonb;
  db_user_id bigint;
begin
  -- Initialize claims to the existing claims object from the event
  claims := event->'claims';

  -- Fetch the user's role, credentials, additional data, and db user id
  select c.role, c.credential, c.additional, u.id
    into user_role, user_credential, user_additional, db_user_id
    from public.claims as c
    join public.users as u on c.user_id = u.id
    where u.auth_id = (event->>'user_id')::uuid;

  -- Check if user data was found
  if db_user_id is null then
    raise notice 'User not found for auth_id: %', event->>'user_id';
    -- Return the original event instead of an error
    return event;
  end if;

  -- Append the user-specific claims to the existing claims object
  claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  claims := jsonb_set(claims, '{user_credential}', to_jsonb(coalesce(user_credential, null)));
  claims := jsonb_set(claims, '{user_additional}', coalesce(user_additional, '{}'::jsonb));
  claims := jsonb_set(claims, '{user_id}', to_jsonb(db_user_id));

  -- Update the 'claims' object in the original event
  event := jsonb_set(event, '{claims}', claims);

  return event;
end;
$$;

-- Trigger that executes 'handle_new_user' after a new row is inserted into 'public.users'.
create trigger on_user_created
  after insert on public.users
  for each row execute procedure public.handle_new_user();

-- Defines the central authorization function used by RLS policies.
create function public.authorize(
  requested_permission public.app_permission
)
returns boolean as $$
declare
  bind_permissions int;
  current_user_role public.app_role;
begin
  -- Retrieves the 'user_role' claim from the current user's JWT.
  -- This will be NULL if the claim is not set or is JSON null.
  select ((select auth.jwt()) ->> 'user_role')::public.app_role into current_user_role;

  -- If current_user_role is NULL (e.g., claim missing, or was explicitly set to null),
  -- then the user has no specific role for permission checking.
  if current_user_role is null then
    return false;
  end if;

  -- Checks if the user's role has the requested permission in the 'role_permissions' table.
  select count(*)
  into bind_permissions
  from public.role_permissions
  where public.role_permissions.permission = requested_permission
    and public.role_permissions.role = current_user_role;
  return bind_permissions > 0;
end;
$$ language plpgsql stable security definer set search_path = '';

-- Policies for "users" table
create policy "Allow users to create their own data" on public.users as permissive for insert to authenticated with check ((select auth.uid()) = auth_id);
create policy "Allow users to update their own data" on public.users as permissive for update to authenticated using (((select auth.jwt()->>'user_id')::bigint) = id) with check ((select auth.uid()) = auth_id);
-- Allows all authenticated users to read user data
create policy "Allow authenticated users to read user data" on public.users as permissive for select to authenticated using (true);
-- Allows users with specific roles to read or update user data based on 'users.write' permissions. Deletion is not directly allowed by these policies.
create policy "Allow user roles to update user data" on public.users as permissive for update to authenticated using (authorize('users.write'));

alter table public.users enable row level security;

-- Allows all authenticated users to read a user's awards
create policy "Allow authenticated users to read user awards" on public.awards as permissive for select to authenticated using (true);
-- Policies for role-based access to awards.
-- Allows users with the 'awards.write' permission to create awards.
create policy "Allow user roles to create awards" on public.awards as permissive for insert to authenticated with check (authorize('awards.write'));
-- Allows users with the 'awards.write' permission to delete awards.
create policy "Allow user roles to delete awards" on public.awards as permissive for delete to authenticated using (authorize('awards.write'));

alter table public.awards enable row level security;

-- Policies for "claims" table
-- Allows any authenticated user to read user claims.
create policy "Allow authenticated users to read user claims" on public.claims as permissive for select to authenticated using (true);

alter table public.claims enable row level security;

-- Policies for "details" table
create policy "Allow users to read their own details" on public.details as permissive for select to authenticated using (((select auth.jwt()->>'user_id')::bigint) = user_id);
create policy "Allow users to update their own details" on public.details as permissive for update to authenticated using (((select auth.jwt()->>'user_id')::bigint) = user_id) with check (((select auth.jwt()->>'user_id')::bigint) = user_id);
-- Policies for role-based access to user details.
-- Allows users with the 'details.read' permission to read user details.
create policy "Allow user roles to read details" on public.details as permissive for select to authenticated using (authorize('details.read'));
-- Allows users with the 'details.write' permission to update user details.
create policy "Allow user roles to update details" on public.details as permissive for update to authenticated using (authorize('details.write')) with check (authorize('details.write'));

alter table public.details enable row level security;

-- Policies for "supervisors" table
create policy "Allow users to read their own supervisor information" on public.supervisors as permissive for select to authenticated using (((select auth.jwt()->>'user_id')::bigint) = user_id);
create policy "Allow users to create their own supervisor information" on public.supervisors as permissive for insert to authenticated with check (((select auth.jwt()->>'user_id')::bigint) = user_id);
create policy "Allow users to update their own supervisor information" on public.supervisors as permissive for update to authenticated using (((select auth.jwt()->>'user_id')::bigint) = user_id) with check (((select auth.jwt()->>'user_id')::bigint) = user_id);
-- Allow users with the 'supervisors.read' permission to read supervisor information.
create policy "Allow user roles to read supervisors" on public.supervisors as permissive for select to authenticated using (authorize('supervisors.read'));
-- Allow users with the 'supervisors.write' permission to create supervisor information.
create policy "Allow user roles to create supervisors" on public.supervisors as permissive for insert to authenticated with check (authorize('supervisors.write'));
-- Allow users with the 'supervisors.write' permission to update supervisor information.
create policy "Allow user roles to update supervisors" on public.supervisors as permissive for update to authenticated using (authorize('supervisors.write')) with check (authorize('supervisors.write'));

alter table public.supervisors enable row level security;

-- Policy for "role_permissions" table
-- Defines a policy allowing the Supabase auth admin to read all entries in the 'role_permissions' table.
create policy "Allow auth admin to read role_permissions" ON public.role_permissions
as permissive for select
to supabase_auth_admin
using (true);

alter table public.role_permissions enable row level security;

-- Grants and Revokes
-- Grants usage of the public schema to the Supabase auth admin role.
grant usage on schema public to supabase_auth_admin;

-- Grants execute permission on the custom JWT hook function to the Supabase auth admin.
grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

-- Revokes execute permission on the custom JWT hook function from general roles to restrict its direct invocation.
revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;

-- Grants all permissions on the 'role_permissions' table to the Supabase auth admin.
grant all
  on table public.role_permissions
to supabase_auth_admin;

-- Revokes all permissions on the 'role_permissions' table from general roles.
revoke all
  on table public.role_permissions
  from authenticated, anon, public;