create extension if not exists "unaccent" with schema "public" version '1.1';

create type "public"."app_permission" as enum ('awards.read', 'awards.write', 'clubs.read', 'clubs.write', 'club_managers.read', 'club_managers.write', 'claims.read', 'claims.write', 'details.read', 'details.write', 'memberships.read', 'memberships.write', 'users.read', 'users.write', 'messages.read', 'messages.write', 'invoices.read', 'invoices.write', 'payment_items.read', 'payment_items.write', 'supervisors.read', 'supervisors.write');

create type "public"."app_role" as enum ('developer', 'admin', 'cap', 'junior_organizer', 'senior_organizer', 'mc_member', 'user');

create type "public"."club_league" as enum ('junior', 'senior', 'university');

create type "public"."message_platform" as enum ('debrief', 'fastballot', 'barca');

create type "public"."message_type" as enum ('text', 'header', 'toast', 'redirect');

create type "public"."payment_status" as enum ('pending', 'completed', 'failed');

CREATE OR REPLACE FUNCTION public.immutable_unaccent(text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select replace(unaccent('unaccent', $1), ' ', '')
$function$
;


create table "public"."awards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "award" text not null,
    "level" smallint not null
);


alter table "public"."awards" enable row level security;

create table "public"."claims" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "role" app_role not null default 'user'::app_role,
    "credential" smallint not null default 0,
    "additional" jsonb not null default '{}'::jsonb
);


alter table "public"."claims" enable row level security;

create table "public"."club_managers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "club_id" bigint not null,
    "user_id" bigint not null
);


alter table "public"."club_managers" enable row level security;

create table "public"."clubs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "active" boolean not null default true,
    "league" club_league not null default 'senior'::club_league,
    "search_index" text generated always as (immutable_unaccent(lower(name))) stored
);


alter table "public"."clubs" enable row level security;

create table "public"."details" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "birthdate" date,
    "address" text,
    "email" text,
    "phone" text
);


alter table "public"."details" enable row level security;

create table "public"."invoices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "amount" numeric(10,2) not null,
    "status" payment_status not null default 'pending'::payment_status
);


alter table "public"."invoices" enable row level security;

create table "public"."memberships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "club_id" bigint not null,
    "year" smallint not null,
    "confirmed" boolean not null default false
);


alter table "public"."memberships" enable row level security;

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" message_type not null default 'text'::message_type,
    "platform" message_platform not null default 'debrief'::message_platform,
    "content" jsonb not null,
    "link" text
);


alter table "public"."messages" enable row level security;

create table "public"."payment_items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "amount" numeric(10,2) not null,
    "comment" text,
    "status" payment_status not null default 'pending'::payment_status,
    "invoice_id" bigint,
    "membership_id" bigint
);


alter table "public"."payment_items" enable row level security;

create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" app_role not null,
    "permission" app_permission not null
);


alter table "public"."role_permissions" enable row level security;

create table "public"."supervisors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "name" text not null,
    "surname" text not null,
    "email" text not null
);


alter table "public"."supervisors" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid default auth.uid(),
    "name" text not null,
    "surname" text not null,
    "public" boolean not null default true,
    "search_index" text generated always as (immutable_unaccent(lower(((name || surname) || name)))) stored
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX awards_pkey ON public.awards USING btree (id);

CREATE UNIQUE INDEX awards_user_id_award_level_key ON public.awards USING btree (user_id, award, level);

CREATE UNIQUE INDEX claims_pkey ON public.claims USING btree (id);

CREATE UNIQUE INDEX claims_user_id_key ON public.claims USING btree (user_id);

CREATE UNIQUE INDEX club_managers_club_id_user_id_key ON public.club_managers USING btree (club_id, user_id);

CREATE UNIQUE INDEX club_managers_pkey ON public.club_managers USING btree (id);

CREATE UNIQUE INDEX clubs_name_league_key ON public.clubs USING btree (name, league);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX details_pkey ON public.details USING btree (id);

CREATE UNIQUE INDEX details_user_id_key ON public.details USING btree (user_id);

CREATE UNIQUE INDEX invoices_pkey ON public.invoices USING btree (id);

CREATE INDEX ix_awards_user_id ON public.awards USING btree (user_id);

CREATE INDEX ix_claims_role ON public.claims USING btree (role);

CREATE INDEX ix_club_managers_club_id ON public.club_managers USING btree (club_id);

CREATE INDEX ix_club_managers_user_id ON public.club_managers USING btree (user_id);

CREATE INDEX ix_clubs_active ON public.clubs USING btree (active);

CREATE INDEX ix_clubs_search_index ON public.clubs USING btree (search_index);

CREATE INDEX ix_invoices_status ON public.invoices USING btree (status);

CREATE INDEX ix_invoices_user_id ON public.invoices USING btree (user_id);

CREATE INDEX ix_memberships_club_id ON public.memberships USING btree (club_id);

CREATE INDEX ix_memberships_confirmed ON public.memberships USING btree (confirmed);

CREATE INDEX ix_memberships_user_id ON public.memberships USING btree (user_id);

CREATE INDEX ix_messages_platform ON public.messages USING btree (platform);

CREATE INDEX ix_messages_type ON public.messages USING btree (type);

CREATE INDEX ix_payment_items_created_at ON public.payment_items USING btree (created_at);

CREATE INDEX ix_payment_items_invoice_id ON public.payment_items USING btree (invoice_id);

CREATE INDEX ix_payment_items_membership_id ON public.payment_items USING btree (membership_id);

CREATE INDEX ix_payment_items_status ON public.payment_items USING btree (status);

CREATE INDEX ix_payment_items_user_id ON public.payment_items USING btree (user_id);

CREATE INDEX ix_users_auth_id ON public.users USING btree (auth_id);

CREATE INDEX ix_users_public ON public.users USING btree (public);

CREATE INDEX ix_users_search_index ON public.users USING btree (search_index);

CREATE UNIQUE INDEX memberships_pkey ON public.memberships USING btree (id);

CREATE UNIQUE INDEX memberships_user_id_club_id_year_key ON public.memberships USING btree (user_id, club_id, year);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX payment_items_pkey ON public.payment_items USING btree (id);

CREATE UNIQUE INDEX payment_items_user_id_key ON public.payment_items USING btree (user_id);

CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);

CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);

CREATE UNIQUE INDEX supervisors_pkey ON public.supervisors USING btree (id);

CREATE UNIQUE INDEX supervisors_user_id_key ON public.supervisors USING btree (user_id);

CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."awards" add constraint "awards_pkey" PRIMARY KEY using index "awards_pkey";

alter table "public"."claims" add constraint "claims_pkey" PRIMARY KEY using index "claims_pkey";

alter table "public"."club_managers" add constraint "club_managers_pkey" PRIMARY KEY using index "club_managers_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."details" add constraint "details_pkey" PRIMARY KEY using index "details_pkey";

alter table "public"."invoices" add constraint "invoices_pkey" PRIMARY KEY using index "invoices_pkey";

alter table "public"."memberships" add constraint "memberships_pkey" PRIMARY KEY using index "memberships_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."payment_items" add constraint "payment_items_pkey" PRIMARY KEY using index "payment_items_pkey";

alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";

alter table "public"."supervisors" add constraint "supervisors_pkey" PRIMARY KEY using index "supervisors_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."awards" add constraint "awards_user_id_award_level_key" UNIQUE using index "awards_user_id_award_level_key";

alter table "public"."awards" add constraint "awards_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."awards" validate constraint "awards_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."claims" validate constraint "claims_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_key" UNIQUE using index "claims_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_club_id_fkey";

alter table "public"."club_managers" add constraint "club_managers_club_id_user_id_key" UNIQUE using index "club_managers_club_id_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_user_id_fkey";

alter table "public"."clubs" add constraint "clubs_name_league_key" UNIQUE using index "clubs_name_league_key";

alter table "public"."details" add constraint "details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."details" validate constraint "details_user_id_fkey";

alter table "public"."details" add constraint "details_user_id_key" UNIQUE using index "details_user_id_key";

alter table "public"."invoices" add constraint "invoices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."invoices" validate constraint "invoices_user_id_fkey";

alter table "public"."memberships" add constraint "memberships_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE not valid;

alter table "public"."memberships" validate constraint "memberships_club_id_fkey";

alter table "public"."memberships" add constraint "memberships_user_id_club_id_year_key" UNIQUE using index "memberships_user_id_club_id_year_key";

alter table "public"."memberships" add constraint "memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."memberships" validate constraint "memberships_user_id_fkey";

alter table "public"."payment_items" add constraint "payment_items_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL not valid;

alter table "public"."payment_items" validate constraint "payment_items_invoice_id_fkey";

alter table "public"."payment_items" add constraint "payment_items_membership_id_fkey" FOREIGN KEY (membership_id) REFERENCES memberships(id) ON DELETE SET NULL not valid;

alter table "public"."payment_items" validate constraint "payment_items_membership_id_fkey";

alter table "public"."payment_items" add constraint "payment_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."payment_items" validate constraint "payment_items_user_id_fkey";

alter table "public"."payment_items" add constraint "payment_items_user_id_key" UNIQUE using index "payment_items_user_id_key";

alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";

alter table "public"."supervisors" add constraint "supervisors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."supervisors" validate constraint "supervisors_user_id_fkey";

alter table "public"."supervisors" add constraint "supervisors_user_id_key" UNIQUE using index "supervisors_user_id_key";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_auth_id_key" UNIQUE using index "users_auth_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  bind_permissions int;
  current_user_role public.app_role;
begin
  -- Retrieves the 'user_role' claim from the current user's JWT.
  -- This will be NULL if the claim is not set or is JSON null.
  select ((select auth.jwt()) ->> 'user_role')::public.app_role into current_user_role;

  -- If current_user_role is NULL (e.g., claim missing, or was explicitly set to null),
  -- then the user has no specific role for permission checking.
  if current_user_role is null then
    return false;
  end if;

  -- Checks if the user's role has the requested permission in the 'role_permissions' table.
  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = current_user_role;
  return bind_permissions > 0;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
declare
  claims jsonb;
  user_role public.app_role;
  user_credential smallint;
  user_additional jsonb;
  db_user_id bigint;
begin
  -- Initialize claims to the existing claims object from the event
  claims := event->'claims';

  -- Fetch the user's role, credentials, additional data, and db user id
  select c.role, c.credential, c.additional, u.id
    into user_role, user_credential, user_additional, db_user_id
    from public.claims as c
    join public.users as u on c.user_id = u.id
    where u.auth_id = (event->>'user_id')::uuid;

  -- Check if user data was found
  if db_user_id is null then
    raise notice 'User not found for auth_id: %', event->>'user_id';
    -- Return an empty claims object instead of an error
    return event;
  end if;

  -- Append the user-specific claims to the existing claims object
  claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));  -- No coalesce here
  claims := jsonb_set(claims, '{user_credential}', to_jsonb(coalesce(user_credential, null)));  -- Use null directly
  claims := jsonb_set(claims, '{user_additional}', coalesce(user_additional, '{}'::jsonb));
  claims := jsonb_set(claims, '{user_id}', to_jsonb(db_user_id));

  -- Update the 'claims' object in the original event
  event := jsonb_set(event, '{claims}', claims);

  -- Return the modified event
  return event;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.claims (user_id, role, credential)
  values (new.id, 'user', 0);
  insert into public.details (user_id)
  values (new.id);
  return new;
end;
$function$
;


CREATE OR REPLACE FUNCTION public.update_payment_item_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    if new.status = 'completed' then
        update payment_items set status = 'completed' where invoice_id = new.id;
    elsif new.status = 'failed' then
        update payment_items set status = 'failed' where invoice_id = new.id;
    end if;
    return new;
end;
$function$
;

grant delete on table "public"."awards" to "anon";

grant insert on table "public"."awards" to "anon";

grant references on table "public"."awards" to "anon";

grant select on table "public"."awards" to "anon";

grant trigger on table "public"."awards" to "anon";

grant truncate on table "public"."awards" to "anon";

grant update on table "public"."awards" to "anon";

grant delete on table "public"."awards" to "authenticated";

grant insert on table "public"."awards" to "authenticated";

grant references on table "public"."awards" to "authenticated";

grant select on table "public"."awards" to "authenticated";

grant trigger on table "public"."awards" to "authenticated";

grant truncate on table "public"."awards" to "authenticated";

grant update on table "public"."awards" to "authenticated";

grant delete on table "public"."awards" to "service_role";

grant insert on table "public"."awards" to "service_role";

grant references on table "public"."awards" to "service_role";

grant select on table "public"."awards" to "service_role";

grant trigger on table "public"."awards" to "service_role";

grant truncate on table "public"."awards" to "service_role";

grant update on table "public"."awards" to "service_role";

grant delete on table "public"."claims" to "anon";

grant insert on table "public"."claims" to "anon";

grant references on table "public"."claims" to "anon";

grant select on table "public"."claims" to "anon";

grant trigger on table "public"."claims" to "anon";

grant truncate on table "public"."claims" to "anon";

grant update on table "public"."claims" to "anon";

grant delete on table "public"."claims" to "authenticated";

grant insert on table "public"."claims" to "authenticated";

grant references on table "public"."claims" to "authenticated";

grant select on table "public"."claims" to "authenticated";

grant trigger on table "public"."claims" to "authenticated";

grant truncate on table "public"."claims" to "authenticated";

grant update on table "public"."claims" to "authenticated";

grant delete on table "public"."claims" to "service_role";

grant insert on table "public"."claims" to "service_role";

grant references on table "public"."claims" to "service_role";

grant select on table "public"."claims" to "service_role";

grant trigger on table "public"."claims" to "service_role";

grant truncate on table "public"."claims" to "service_role";

grant update on table "public"."claims" to "service_role";

grant delete on table "public"."club_managers" to "anon";

grant insert on table "public"."club_managers" to "anon";

grant references on table "public"."club_managers" to "anon";

grant select on table "public"."club_managers" to "anon";

grant trigger on table "public"."club_managers" to "anon";

grant truncate on table "public"."club_managers" to "anon";

grant update on table "public"."club_managers" to "anon";

grant delete on table "public"."club_managers" to "authenticated";

grant insert on table "public"."club_managers" to "authenticated";

grant references on table "public"."club_managers" to "authenticated";

grant select on table "public"."club_managers" to "authenticated";

grant trigger on table "public"."club_managers" to "authenticated";

grant truncate on table "public"."club_managers" to "authenticated";

grant update on table "public"."club_managers" to "authenticated";

grant delete on table "public"."club_managers" to "service_role";

grant insert on table "public"."club_managers" to "service_role";

grant references on table "public"."club_managers" to "service_role";

grant select on table "public"."club_managers" to "service_role";

grant trigger on table "public"."club_managers" to "service_role";

grant truncate on table "public"."club_managers" to "service_role";

grant update on table "public"."club_managers" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."details" to "anon";

grant insert on table "public"."details" to "anon";

grant references on table "public"."details" to "anon";

grant select on table "public"."details" to "anon";

grant trigger on table "public"."details" to "anon";

grant truncate on table "public"."details" to "anon";

grant update on table "public"."details" to "anon";

grant delete on table "public"."details" to "authenticated";

grant insert on table "public"."details" to "authenticated";

grant references on table "public"."details" to "authenticated";

grant select on table "public"."details" to "authenticated";

grant trigger on table "public"."details" to "authenticated";

grant truncate on table "public"."details" to "authenticated";

grant update on table "public"."details" to "authenticated";

grant delete on table "public"."details" to "service_role";

grant insert on table "public"."details" to "service_role";

grant references on table "public"."details" to "service_role";

grant select on table "public"."details" to "service_role";

grant trigger on table "public"."details" to "service_role";

grant truncate on table "public"."details" to "service_role";

grant update on table "public"."details" to "service_role";

grant delete on table "public"."invoices" to "anon";

grant insert on table "public"."invoices" to "anon";

grant references on table "public"."invoices" to "anon";

grant select on table "public"."invoices" to "anon";

grant trigger on table "public"."invoices" to "anon";

grant truncate on table "public"."invoices" to "anon";

grant update on table "public"."invoices" to "anon";

grant delete on table "public"."invoices" to "authenticated";

grant insert on table "public"."invoices" to "authenticated";

grant references on table "public"."invoices" to "authenticated";

grant select on table "public"."invoices" to "authenticated";

grant trigger on table "public"."invoices" to "authenticated";

grant truncate on table "public"."invoices" to "authenticated";

grant update on table "public"."invoices" to "authenticated";

grant delete on table "public"."invoices" to "service_role";

grant insert on table "public"."invoices" to "service_role";

grant references on table "public"."invoices" to "service_role";

grant select on table "public"."invoices" to "service_role";

grant trigger on table "public"."invoices" to "service_role";

grant truncate on table "public"."invoices" to "service_role";

grant update on table "public"."invoices" to "service_role";

grant delete on table "public"."memberships" to "anon";

grant insert on table "public"."memberships" to "anon";

grant references on table "public"."memberships" to "anon";

grant select on table "public"."memberships" to "anon";

grant trigger on table "public"."memberships" to "anon";

grant truncate on table "public"."memberships" to "anon";

grant update on table "public"."memberships" to "anon";

grant delete on table "public"."memberships" to "authenticated";

grant insert on table "public"."memberships" to "authenticated";

grant references on table "public"."memberships" to "authenticated";

grant select on table "public"."memberships" to "authenticated";

grant trigger on table "public"."memberships" to "authenticated";

grant truncate on table "public"."memberships" to "authenticated";

grant update on table "public"."memberships" to "authenticated";

grant delete on table "public"."memberships" to "service_role";

grant insert on table "public"."memberships" to "service_role";

grant references on table "public"."memberships" to "service_role";

grant select on table "public"."memberships" to "service_role";

grant trigger on table "public"."memberships" to "service_role";

grant truncate on table "public"."memberships" to "service_role";

grant update on table "public"."memberships" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."payment_items" to "anon";

grant insert on table "public"."payment_items" to "anon";

grant references on table "public"."payment_items" to "anon";

grant select on table "public"."payment_items" to "anon";

grant trigger on table "public"."payment_items" to "anon";

grant truncate on table "public"."payment_items" to "anon";

grant update on table "public"."payment_items" to "anon";

grant delete on table "public"."payment_items" to "authenticated";

grant insert on table "public"."payment_items" to "authenticated";

grant references on table "public"."payment_items" to "authenticated";

grant select on table "public"."payment_items" to "authenticated";

grant trigger on table "public"."payment_items" to "authenticated";

grant truncate on table "public"."payment_items" to "authenticated";

grant update on table "public"."payment_items" to "authenticated";

grant delete on table "public"."payment_items" to "service_role";

grant insert on table "public"."payment_items" to "service_role";

grant references on table "public"."payment_items" to "service_role";

grant select on table "public"."payment_items" to "service_role";

grant trigger on table "public"."payment_items" to "service_role";

grant truncate on table "public"."payment_items" to "service_role";

grant update on table "public"."payment_items" to "service_role";

grant delete on table "public"."role_permissions" to "service_role";

grant insert on table "public"."role_permissions" to "service_role";

grant references on table "public"."role_permissions" to "service_role";

grant select on table "public"."role_permissions" to "service_role";

grant trigger on table "public"."role_permissions" to "service_role";

grant truncate on table "public"."role_permissions" to "service_role";

grant update on table "public"."role_permissions" to "service_role";

grant delete on table "public"."role_permissions" to "supabase_auth_admin";

grant insert on table "public"."role_permissions" to "supabase_auth_admin";

grant references on table "public"."role_permissions" to "supabase_auth_admin";

grant select on table "public"."role_permissions" to "supabase_auth_admin";

grant trigger on table "public"."role_permissions" to "supabase_auth_admin";

grant truncate on table "public"."role_permissions" to "supabase_auth_admin";

grant update on table "public"."role_permissions" to "supabase_auth_admin";

grant delete on table "public"."supervisors" to "anon";

grant insert on table "public"."supervisors" to "anon";

grant references on table "public"."supervisors" to "anon";

grant select on table "public"."supervisors" to "anon";

grant trigger on table "public"."supervisors" to "anon";

grant truncate on table "public"."supervisors" to "anon";

grant update on table "public"."supervisors" to "anon";

grant delete on table "public"."supervisors" to "authenticated";

grant insert on table "public"."supervisors" to "authenticated";

grant references on table "public"."supervisors" to "authenticated";

grant select on table "public"."supervisors" to "authenticated";

grant trigger on table "public"."supervisors" to "authenticated";

grant truncate on table "public"."supervisors" to "authenticated";

grant update on table "public"."supervisors" to "authenticated";

grant delete on table "public"."supervisors" to "service_role";

grant insert on table "public"."supervisors" to "service_role";

grant references on table "public"."supervisors" to "service_role";

grant select on table "public"."supervisors" to "service_role";

grant trigger on table "public"."supervisors" to "service_role";

grant truncate on table "public"."supervisors" to "service_role";

grant update on table "public"."supervisors" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Allow authenticated users to read public user awards"
on "public"."awards"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = awards.user_id) AND (users.public = true)))));


create policy "Allow user roles to create awards"
on "public"."awards"
as permissive
for insert
to authenticated
with check (authorize('awards.write'::app_permission));


create policy "Allow user roles to delete awards"
on "public"."awards"
as permissive
for delete
to authenticated
using (authorize('awards.write'::app_permission));


create policy "Allow user roles to read awards"
on "public"."awards"
as permissive
for select
to authenticated
using (authorize('awards.read'::app_permission));


create policy "Allow user roles to update awards"
on "public"."awards"
as permissive
for update
to authenticated
using (authorize('awards.write'::app_permission));


create policy "Allow users to read their own awards"
on "public"."awards"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow authenticated users to read user claims"
on "public"."claims"
as permissive
for select
to authenticated
using (true);


create policy "Allow authenticated users to read club managers for active club"
on "public"."club_managers"
as permissive
for select
to authenticated;


create policy "Allow users with club_managers.read to read club managers"
on "public"."club_managers"
as permissive
for select
to authenticated
using (authorize('club_managers.read'::app_permission));


create policy "Allow users with club_managers.write to create club managers"
on "public"."club_managers"
as permissive
for insert
to authenticated
with check (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to delete club managers"
on "public"."club_managers"
as permissive
for delete
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to update club managers"
on "public"."club_managers"
as permissive
for update
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Club managers can add managers to their own clubs"
on "public"."club_managers"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM club_managers club_managers_1
  WHERE ((club_managers_1.club_id = club_managers_1.club_id) AND (club_managers_1.user_id = (( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint)))));


create policy "Allow authenticated users to read active clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using ((active = true));


create policy "Allow club managers to update their clubs"
on "public"."clubs"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM club_managers
  WHERE ((club_managers.club_id = clubs.id) AND (club_managers.user_id = ( SELECT users.id
           FROM users
          WHERE (users.auth_id = ( SELECT auth.uid() AS uid))))))));


create policy "Allow users with clubs.read to read clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using (authorize('clubs.read'::app_permission));


create policy "Allow users with clubs.write to create clubs"
on "public"."clubs"
as permissive
for insert
to authenticated
with check (authorize('clubs.write'::app_permission));


create policy "Allow users with clubs.write to update clubs"
on "public"."clubs"
as permissive
for update
to authenticated
using (authorize('clubs.write'::app_permission));


create policy "Allow user roles to read details"
on "public"."details"
as permissive
for select
to authenticated
using (authorize('details.read'::app_permission));


create policy "Allow user roles to update details"
on "public"."details"
as permissive
for update
to authenticated
using (authorize('details.write'::app_permission))
with check (authorize('details.write'::app_permission));


create policy "Allow users to read their own details"
on "public"."details"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users to update their own details"
on "public"."details"
as permissive
for update
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id))
with check (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow authenticated users to read their own invoices"
on "public"."invoices"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users with invoices.read to read invoices"
on "public"."invoices"
as permissive
for select
to authenticated
using (authorize('invoices.read'::app_permission));


create policy "Allow users with invoices.write to update invoices"
on "public"."invoices"
as permissive
for update
to authenticated
using (authorize('invoices.write'::app_permission));


create policy "Allow authenticated users to read public memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = memberships.user_id) AND (users.public = true)))));


create policy "Allow user roles to read memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using (authorize('memberships.read'::app_permission));


create policy "Allow user roles to update memberships"
on "public"."memberships"
as permissive
for update
to authenticated
using (authorize('memberships.write'::app_permission))
with check (authorize('memberships.write'::app_permission));


create policy "Allow users to create their own memberships"
on "public"."memberships"
as permissive
for insert
to authenticated
with check (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users to read their own memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow authenticated users to read messages"
on "public"."messages"
as permissive
for select
to authenticated
using (true);


create policy "Allow users with messages.write to create messages"
on "public"."messages"
as permissive
for insert
to authenticated
with check (authorize('messages.write'::app_permission));


create policy "Allow users with messages.write to delete messages"
on "public"."messages"
as permissive
for delete
to authenticated
using (authorize('messages.write'::app_permission));


create policy "Allow users with messages.write to update messages"
on "public"."messages"
as permissive
for update
to authenticated
using (authorize('messages.write'::app_permission));


create policy "Allow authenticated users to read their own payment_items"
on "public"."payment_items"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users with payment_items.delete to delete payment_items"
on "public"."payment_items"
as permissive
for delete
to authenticated
using (authorize('payment_items.write'::app_permission));


create policy "Allow users with payment_items.read to read payment_items"
on "public"."payment_items"
as permissive
for select
to authenticated
using (authorize('payment_items.read'::app_permission));


create policy "Allow users with payment_items.write to create payment_items"
on "public"."payment_items"
as permissive
for insert
to authenticated
with check (authorize('payment_items.write'::app_permission));


create policy "Allow users with payment_items.write to update payment_items"
on "public"."payment_items"
as permissive
for update
to authenticated
using (authorize('payment_items.write'::app_permission));


create policy "Allow auth admin to read role_permissions"
on "public"."role_permissions"
as permissive
for select
to supabase_auth_admin
using (true);


create policy "Allow user roles to create supervisors"
on "public"."supervisors"
as permissive
for insert
to authenticated
with check (authorize('supervisors.write'::app_permission));


create policy "Allow user roles to read supervisors"
on "public"."supervisors"
as permissive
for select
to authenticated
using (authorize('supervisors.read'::app_permission));


create policy "Allow user roles to update supervisors"
on "public"."supervisors"
as permissive
for update
to authenticated
using (authorize('supervisors.write'::app_permission))
with check (authorize('supervisors.write'::app_permission));


create policy "Allow users to create their own supervisor information"
on "public"."supervisors"
as permissive
for insert
to authenticated
with check (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users to read their own supervisor information"
on "public"."supervisors"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users to update their own supervisor information"
on "public"."supervisors"
as permissive
for update
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id))
with check (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow authenticated users to read public user data"
on "public"."users"
as permissive
for select
to authenticated
using ((public = true));


create policy "Allow user roles to read user data"
on "public"."users"
as permissive
for select
to authenticated
using (authorize('users.read'::app_permission));


create policy "Allow user roles to update user data"
on "public"."users"
as permissive
for update
to authenticated
using (authorize('users.write'::app_permission));


create policy "Allow users to create their own data"
on "public"."users"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = auth_id));


create policy "Allow users to read their own data"
on "public"."users"
as permissive
for select
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = id));


create policy "Allow users to update their own data"
on "public"."users"
as permissive
for update
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = id))
with check ((( SELECT auth.uid() AS uid) = auth_id));


CREATE TRIGGER trg_update_payment_item_status AFTER UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION update_payment_item_status();

CREATE TRIGGER on_user_created AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();


