create type "public"."app_permission" as enum ('awards.read', 'awards.write', 'clubs.read', 'clubs.write', 'club_managers.read', 'club_managers.write', 'claims.read', 'claims.write', 'details.read', 'details.write', 'memberships.read', 'memberships.write', 'users.read', 'users.write');

create type "public"."app_role" as enum ('developer', 'admin', 'cap', 'junior_organizer', 'senior_organizer', 'mc_member', 'user');

create table "public"."awards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "award" text not null,
    "level" smallint not null
);


create table "public"."claims" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "role" app_role not null default 'user'::app_role,
    "credential" smallint not null default 0
);


create table "public"."club_managers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "club_id" bigint not null,
    "user_id" bigint not null
);


create table "public"."clubs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "active" boolean not null default true,
    "league" text not null default 'senior'::text
);


create table "public"."details" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "birthdate" date,
    "address" text,
    "email" text,
    "phone" text
);


create table "public"."memberships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "club_id" bigint not null,
    "year" smallint not null
);


create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" app_role not null,
    "permission" app_permission not null
);


create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid default auth.uid(),
    "name" text,
    "surname" text,
    "public" boolean not null default false
);


CREATE UNIQUE INDEX awards_pkey ON public.awards USING btree (id);

CREATE UNIQUE INDEX awards_user_id_award_level_key ON public.awards USING btree (user_id, award, level);

CREATE UNIQUE INDEX claims_pkey ON public.claims USING btree (id);

CREATE UNIQUE INDEX claims_user_id_key ON public.claims USING btree (user_id);

CREATE UNIQUE INDEX club_managers_club_id_user_id_key ON public.club_managers USING btree (club_id, user_id);

CREATE UNIQUE INDEX club_managers_pkey ON public.club_managers USING btree (id);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX details_pkey ON public.details USING btree (id);

CREATE UNIQUE INDEX details_user_id_key ON public.details USING btree (user_id);

CREATE UNIQUE INDEX memberships_pkey ON public.memberships USING btree (id);

CREATE UNIQUE INDEX memberships_user_id_club_id_year_key ON public.memberships USING btree (user_id, club_id, year);

CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);

CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);

CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."awards" add constraint "awards_pkey" PRIMARY KEY using index "awards_pkey";

alter table "public"."claims" add constraint "claims_pkey" PRIMARY KEY using index "claims_pkey";

alter table "public"."club_managers" add constraint "club_managers_pkey" PRIMARY KEY using index "club_managers_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."details" add constraint "details_pkey" PRIMARY KEY using index "details_pkey";

alter table "public"."memberships" add constraint "memberships_pkey" PRIMARY KEY using index "memberships_pkey";

alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."awards" add constraint "awards_user_id_award_level_key" UNIQUE using index "awards_user_id_award_level_key";

alter table "public"."awards" add constraint "awards_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."awards" validate constraint "awards_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."claims" validate constraint "claims_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_key" UNIQUE using index "claims_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_club_id_fkey";

alter table "public"."club_managers" add constraint "club_managers_club_id_user_id_key" UNIQUE using index "club_managers_club_id_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_user_id_fkey";

alter table "public"."details" add constraint "details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."details" validate constraint "details_user_id_fkey";

alter table "public"."details" add constraint "details_user_id_key" UNIQUE using index "details_user_id_key";

alter table "public"."memberships" add constraint "memberships_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) not valid;

alter table "public"."memberships" validate constraint "memberships_club_id_fkey";

alter table "public"."memberships" add constraint "memberships_user_id_club_id_year_key" UNIQUE using index "memberships_user_id_club_id_year_key";

alter table "public"."memberships" add constraint "memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."memberships" validate constraint "memberships_user_id_fkey";

alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_auth_id_key" UNIQUE using index "users_auth_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  bind_permissions int;
  current_user_role public.app_role;
begin
  -- Retrieves the 'user_role' claim from the current user's JWT.
  -- This will be NULL if the claim is not set or is JSON null.
  select (auth.jwt() ->> 'user_role')::public.app_role into current_user_role;

  -- If current_user_role is NULL (e.g., claim missing, or was explicitly set to null),
  -- then the user has no specific role for permission checking.
  if current_user_role is null then
    return false;
  end if;

  -- Checks if the user's role has the requested permission in the 'role_permissions' table.
  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = current_user_role;
  return bind_permissions > 0;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
  declare
    claims_from_event jsonb;
    user_role public.app_role;
  begin
    -- Fetches the user's application role from the 'claims' table.
    select c.role
    into user_role
    from public.claims as c
    join public.users as u on c.user_id = u.id
    where u.auth_id = (event->>'user_id')::uuid;

    claims_from_event := event->'claims';

    if user_role is not null then
      -- Sets the 'user_role' claim in the JWT.
      claims_from_event := jsonb_set(claims_from_event, '{user_role}', to_jsonb(user_role));
    else
      -- Sets the 'user_role' claim to JSON null if the user_role is not found.
      claims_from_event := jsonb_set(claims_from_event, '{user_role}', to_jsonb(null::public.app_role));
    end if;

    -- Updates the 'claims' object within the original event JSON.
    event := jsonb_set(event, '{claims}', claims_from_event);

    -- Returns the modified event with the new claim.
    return event;
  end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.claims (user_id, role, credential)
  values (new.id, 'user', 0);
  insert into public.details (user_id)
  values (new.id);
  return new;
end;
$function$
;

grant delete on table "public"."awards" to "anon";

grant insert on table "public"."awards" to "anon";

grant references on table "public"."awards" to "anon";

grant select on table "public"."awards" to "anon";

grant trigger on table "public"."awards" to "anon";

grant truncate on table "public"."awards" to "anon";

grant update on table "public"."awards" to "anon";

grant delete on table "public"."awards" to "authenticated";

grant insert on table "public"."awards" to "authenticated";

grant references on table "public"."awards" to "authenticated";

grant select on table "public"."awards" to "authenticated";

grant trigger on table "public"."awards" to "authenticated";

grant truncate on table "public"."awards" to "authenticated";

grant update on table "public"."awards" to "authenticated";

grant delete on table "public"."awards" to "service_role";

grant insert on table "public"."awards" to "service_role";

grant references on table "public"."awards" to "service_role";

grant select on table "public"."awards" to "service_role";

grant trigger on table "public"."awards" to "service_role";

grant truncate on table "public"."awards" to "service_role";

grant update on table "public"."awards" to "service_role";

grant delete on table "public"."claims" to "anon";

grant insert on table "public"."claims" to "anon";

grant references on table "public"."claims" to "anon";

grant select on table "public"."claims" to "anon";

grant trigger on table "public"."claims" to "anon";

grant truncate on table "public"."claims" to "anon";

grant update on table "public"."claims" to "anon";

grant delete on table "public"."claims" to "authenticated";

grant insert on table "public"."claims" to "authenticated";

grant references on table "public"."claims" to "authenticated";

grant select on table "public"."claims" to "authenticated";

grant trigger on table "public"."claims" to "authenticated";

grant truncate on table "public"."claims" to "authenticated";

grant update on table "public"."claims" to "authenticated";

grant delete on table "public"."claims" to "service_role";

grant insert on table "public"."claims" to "service_role";

grant references on table "public"."claims" to "service_role";

grant select on table "public"."claims" to "service_role";

grant trigger on table "public"."claims" to "service_role";

grant truncate on table "public"."claims" to "service_role";

grant update on table "public"."claims" to "service_role";

grant delete on table "public"."club_managers" to "anon";

grant insert on table "public"."club_managers" to "anon";

grant references on table "public"."club_managers" to "anon";

grant select on table "public"."club_managers" to "anon";

grant trigger on table "public"."club_managers" to "anon";

grant truncate on table "public"."club_managers" to "anon";

grant update on table "public"."club_managers" to "anon";

grant delete on table "public"."club_managers" to "authenticated";

grant insert on table "public"."club_managers" to "authenticated";

grant references on table "public"."club_managers" to "authenticated";

grant select on table "public"."club_managers" to "authenticated";

grant trigger on table "public"."club_managers" to "authenticated";

grant truncate on table "public"."club_managers" to "authenticated";

grant update on table "public"."club_managers" to "authenticated";

grant delete on table "public"."club_managers" to "service_role";

grant insert on table "public"."club_managers" to "service_role";

grant references on table "public"."club_managers" to "service_role";

grant select on table "public"."club_managers" to "service_role";

grant trigger on table "public"."club_managers" to "service_role";

grant truncate on table "public"."club_managers" to "service_role";

grant update on table "public"."club_managers" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."details" to "anon";

grant insert on table "public"."details" to "anon";

grant references on table "public"."details" to "anon";

grant select on table "public"."details" to "anon";

grant trigger on table "public"."details" to "anon";

grant truncate on table "public"."details" to "anon";

grant update on table "public"."details" to "anon";

grant delete on table "public"."details" to "authenticated";

grant insert on table "public"."details" to "authenticated";

grant references on table "public"."details" to "authenticated";

grant select on table "public"."details" to "authenticated";

grant trigger on table "public"."details" to "authenticated";

grant truncate on table "public"."details" to "authenticated";

grant update on table "public"."details" to "authenticated";

grant delete on table "public"."details" to "service_role";

grant insert on table "public"."details" to "service_role";

grant references on table "public"."details" to "service_role";

grant select on table "public"."details" to "service_role";

grant trigger on table "public"."details" to "service_role";

grant truncate on table "public"."details" to "service_role";

grant update on table "public"."details" to "service_role";

grant delete on table "public"."memberships" to "anon";

grant insert on table "public"."memberships" to "anon";

grant references on table "public"."memberships" to "anon";

grant select on table "public"."memberships" to "anon";

grant trigger on table "public"."memberships" to "anon";

grant truncate on table "public"."memberships" to "anon";

grant update on table "public"."memberships" to "anon";

grant delete on table "public"."memberships" to "authenticated";

grant insert on table "public"."memberships" to "authenticated";

grant references on table "public"."memberships" to "authenticated";

grant select on table "public"."memberships" to "authenticated";

grant trigger on table "public"."memberships" to "authenticated";

grant truncate on table "public"."memberships" to "authenticated";

grant update on table "public"."memberships" to "authenticated";

grant delete on table "public"."memberships" to "service_role";

grant insert on table "public"."memberships" to "service_role";

grant references on table "public"."memberships" to "service_role";

grant select on table "public"."memberships" to "service_role";

grant trigger on table "public"."memberships" to "service_role";

grant truncate on table "public"."memberships" to "service_role";

grant update on table "public"."memberships" to "service_role";

grant delete on table "public"."role_permissions" to "service_role";

grant insert on table "public"."role_permissions" to "service_role";

grant references on table "public"."role_permissions" to "service_role";

grant select on table "public"."role_permissions" to "service_role";

grant trigger on table "public"."role_permissions" to "service_role";

grant truncate on table "public"."role_permissions" to "service_role";

grant update on table "public"."role_permissions" to "service_role";

grant delete on table "public"."role_permissions" to "supabase_auth_admin";

grant insert on table "public"."role_permissions" to "supabase_auth_admin";

grant references on table "public"."role_permissions" to "supabase_auth_admin";

grant select on table "public"."role_permissions" to "supabase_auth_admin";

grant trigger on table "public"."role_permissions" to "supabase_auth_admin";

grant truncate on table "public"."role_permissions" to "supabase_auth_admin";

grant update on table "public"."role_permissions" to "supabase_auth_admin";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Allow authenticated users to read public user awards"
on "public"."awards"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = awards.user_id) AND (users.public = true)))));


create policy "Allow user roles to create awards"
on "public"."awards"
as permissive
for insert
to authenticated
with check (authorize('awards.write'::app_permission));


create policy "Allow user roles to delete awards"
on "public"."awards"
as permissive
for delete
to authenticated
using (authorize('awards.write'::app_permission));


create policy "Allow user roles to read awards"
on "public"."awards"
as permissive
for select
to authenticated
using (authorize('awards.read'::app_permission));


create policy "Allow user roles to update awards"
on "public"."awards"
as permissive
for update
to authenticated
using (authorize('awards.write'::app_permission));


create policy "Allow users to read their own awards"
on "public"."awards"
as permissive
for select
to authenticated
using ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = awards.user_id))));


create policy "Allow anyone to read user claims"
on "public"."claims"
as permissive
for select
to public
using (true);


create policy "Allow user roles to update user claims"
on "public"."claims"
as permissive
for update
to authenticated
using (authorize('claims.write'::app_permission))
with check (authorize('claims.write'::app_permission));


create policy "Allow authenticated users to read club managers for active club"
on "public"."club_managers"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM clubs
  WHERE ((clubs.id = club_managers.club_id) AND (clubs.active = true)))) AND (EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = club_managers.user_id) AND (users.public = true))))));


create policy "Allow users with club_managers.read to read club managers"
on "public"."club_managers"
as permissive
for select
to authenticated
using (authorize('club_managers.read'::app_permission));


create policy "Allow users with club_managers.write to create club managers"
on "public"."club_managers"
as permissive
for insert
to authenticated
with check (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to delete club managers"
on "public"."club_managers"
as permissive
for delete
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to update club managers"
on "public"."club_managers"
as permissive
for update
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Allow authenticated users to read active clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using ((active = true));


create policy "Allow club managers to read their clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM club_managers
  WHERE ((club_managers.club_id = clubs.id) AND (club_managers.user_id = ( SELECT users.id
           FROM users
          WHERE (users.auth_id = auth.uid())))))));


create policy "Allow club managers to update their clubs"
on "public"."clubs"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM club_managers
  WHERE ((club_managers.club_id = clubs.id) AND (club_managers.user_id = ( SELECT users.id
           FROM users
          WHERE (users.auth_id = auth.uid())))))));


create policy "Allow users with clubs.read to read clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using (authorize('clubs.read'::app_permission));


create policy "Allow users with clubs.write to create clubs"
on "public"."clubs"
as permissive
for insert
to authenticated
with check (authorize('clubs.write'::app_permission));


create policy "Allow users with clubs.write to update clubs"
on "public"."clubs"
as permissive
for update
to authenticated
using (authorize('clubs.write'::app_permission));


create policy "Allow user roles to read details"
on "public"."details"
as permissive
for select
to authenticated
using (authorize('details.read'::app_permission));


create policy "Allow user roles to update details"
on "public"."details"
as permissive
for update
to authenticated
using (authorize('details.write'::app_permission))
with check (authorize('details.write'::app_permission));


create policy "Allow users to read their own details"
on "public"."details"
as permissive
for select
to authenticated
using ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = details.user_id))));


create policy "Allow users to update their own details"
on "public"."details"
as permissive
for update
to authenticated
using ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = details.user_id))))
with check ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = details.user_id))));


create policy "Allow authenticated users to read public memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = memberships.user_id) AND (users.public = true)))));


create policy "Allow user roles to read memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using (authorize('memberships.read'::app_permission));


create policy "Allow user roles to update memberships"
on "public"."memberships"
as permissive
for update
to authenticated
using (authorize('memberships.write'::app_permission))
with check (authorize('memberships.write'::app_permission));


create policy "Allow users to create their own memberships"
on "public"."memberships"
as permissive
for insert
to authenticated
with check ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = memberships.user_id))));


create policy "Allow users to read their own memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = memberships.user_id))));


create policy "Allow users to update their own memberships"
on "public"."memberships"
as permissive
for update
to authenticated
using ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = memberships.user_id))))
with check ((auth.uid() = ( SELECT users.auth_id
   FROM users
  WHERE (users.id = memberships.user_id))));


create policy "Allow auth admin to read role_permissions"
on "public"."role_permissions"
as permissive
for select
to supabase_auth_admin
using (true);


create policy "Allow authenticated users to read public user data"
on "public"."users"
as permissive
for select
to authenticated
using ((public = true));


create policy "Allow user roles to read user data"
on "public"."users"
as permissive
for select
to authenticated
using (authorize('users.read'::app_permission));


create policy "Allow user roles to update user data"
on "public"."users"
as permissive
for update
to authenticated
using (authorize('users.write'::app_permission));


create policy "Allow users to create their own data"
on "public"."users"
as permissive
for insert
to authenticated
with check ((auth.uid() = auth_id));


create policy "Allow users to read their own data"
on "public"."users"
as permissive
for select
to authenticated
using ((auth.uid() = auth_id));


create policy "Allow users to update their own data"
on "public"."users"
as permissive
for update
to authenticated
using ((auth.uid() = auth_id))
with check ((auth.uid() = auth_id));


CREATE TRIGGER on_user_created AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();


