create extension if not exists "unaccent" with schema "extensions";


create type "public"."adjudicator_role" as enum ('adjudicator', 'trainee', 'chair');

create type "public"."app_permission" as enum ('awards.write', 'clubs.read', 'clubs.write', 'club_managers.read', 'club_managers.write', 'details.read', 'details.write', 'memberships.read', 'memberships.write', 'users.write', 'messages.read', 'messages.write', 'invoices.read', 'invoices.write', 'payments.read', 'payments.write', 'supervisors.read', 'supervisors.write', 'events.read', 'events.write', 'motions.read', 'motions.write', 'teams.read', 'teams.write', 'results.read', 'results.write');

create type "public"."app_role" as enum ('developer', 'admin', 'cap', 'junior_organizer', 'senior_organizer', 'mc_member', 'user');

create type "public"."club_league" as enum ('junior', 'senior', 'university');

create type "public"."event_status" as enum ('ongoing', 'completed', 'cancelled');

create type "public"."event_type" as enum ('tournament', 'seminar', 'other');

create type "public"."message_platform" as enum ('debrief', 'fastballot', 'barca');

create type "public"."message_type" as enum ('text', 'header', 'toast', 'redirect');

create type "public"."motion_type" as enum ('prepared', 'impromptu');

create type "public"."payment_status" as enum ('pending', 'completed', 'failed');

create type "public"."round_status" as enum ('scheduled', 'in_progress', 'completed');

create type "public"."round_type" as enum ('preliminary', 'elimination');

create type "public"."supplement_type" as enum ('cross', 'reply');

create type "public"."team_type" as enum ('active', 'archived');

CREATE OR REPLACE FUNCTION public.create_search(text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select regexp_replace(extensions.unaccent($1), '[^a-zA-Z0-9]', '', 'g');
$function$
;

create table "public"."adjudicator_assignments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "debate_id" bigint not null,
    "user_id" bigint not null,
    "role" adjudicator_role not null default 'adjudicator'::adjudicator_role
);


alter table "public"."adjudicator_assignments" enable row level security;

create table "public"."awards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "awarded_by" bigint default (current_setting('jwt.claims.user_id'::text))::bigint,
    "user_id" bigint not null,
    "award" text not null,
    "level" smallint not null
);


alter table "public"."awards" enable row level security;

create table "public"."claims" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "role" app_role not null default 'user'::app_role,
    "credential" smallint not null default 0,
    "additional" jsonb not null default '{}'::jsonb
);


alter table "public"."claims" enable row level security;

create table "public"."club_managers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "club_id" bigint not null,
    "user_id" bigint not null
);


alter table "public"."club_managers" enable row level security;

create table "public"."clubs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "active" boolean not null default true,
    "league" club_league not null default 'senior'::club_league,
    "search_index" text generated always as (create_search(lower(name))) stored
);


alter table "public"."clubs" enable row level security;

create table "public"."debater_scores" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "team_score_id" bigint not null,
    "position" integer not null,
    "score" integer not null,
    "categories" jsonb not null default '{}'::jsonb
);


alter table "public"."debater_scores" enable row level security;

create table "public"."debates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "round_id" bigint not null,
    "room" text not null
);


alter table "public"."debates" enable row level security;

create table "public"."details" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "birthdate" date,
    "address" text,
    "email" text,
    "phone" text,
    "socials" text[] default '{}'::text[]
);


alter table "public"."details" enable row level security;

create table "public"."event_organizers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint not null,
    "user_id" bigint not null,
    "contact_info" jsonb not null default '{}'::jsonb
);


alter table "public"."event_organizers" enable row level security;

create table "public"."event_registrations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint not null,
    "user_id" bigint,
    "role" text not null default 'participant'::text,
    "data" jsonb not null default '{}'::jsonb
);


alter table "public"."event_registrations" enable row level security;

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "type" event_type not null default 'other'::event_type,
    "status" event_status not null default 'ongoing'::event_status,
    "external" text,
    "draft" boolean not null default false,
    "data" jsonb not null default '{}'::jsonb,
    "registration_data" jsonb not null default '{}'::jsonb,
    "search_index" text generated always as (create_search(lower(name))) stored
);


alter table "public"."events" enable row level security;

create table "public"."invoices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "amount" numeric(10,2) not null,
    "status" payment_status not null default 'pending'::payment_status
);


alter table "public"."invoices" enable row level security;

create table "public"."memberships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "club_id" bigint not null,
    "year" smallint not null,
    "confirmed" boolean not null default false
);


alter table "public"."memberships" enable row level security;

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" message_type not null default 'text'::message_type,
    "platform" message_platform not null default 'debrief'::message_platform,
    "content" jsonb not null,
    "link" text
);


alter table "public"."messages" enable row level security;

create table "public"."motions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "motion_type" motion_type not null default 'prepared'::motion_type,
    "motion_text" text not null,
    "event_id" bigint not null,
    "infoslide" text
);


alter table "public"."motions" enable row level security;

create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "amount" numeric(10,2) not null,
    "comment" text,
    "invoice_id" bigint
);


alter table "public"."payments" enable row level security;

create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" app_role not null,
    "permission" app_permission not null
);


alter table "public"."role_permissions" enable row level security;

create table "public"."rounds" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint not null,
    "motion_id" bigint,
    "name" text not null,
    "type" round_type not null default 'preliminary'::round_type,
    "status" round_status not null default 'scheduled'::round_status
);


alter table "public"."rounds" enable row level security;

create table "public"."supervisors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "name" text not null,
    "surname" text not null,
    "email" text not null
);


alter table "public"."supervisors" enable row level security;

create table "public"."supplementary_speeches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team_score_id" bigint not null,
    "type" supplement_type not null default 'cross'::supplement_type,
    "score" integer not null,
    "categories" jsonb not null default '{}'::jsonb
);


alter table "public"."supplementary_speeches" enable row level security;

create table "public"."team_assignments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "debate_id" bigint not null,
    "team_id" bigint not null,
    "side" text not null default 'affirmative'::text
);


alter table "public"."team_assignments" enable row level security;

create table "public"."team_memberships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team_id" bigint not null,
    "user_id" bigint not null,
    "event_id" bigint not null
);


alter table "public"."team_memberships" enable row level security;

create table "public"."team_scores" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team_id" bigint not null,
    "debate_id" bigint not null,
    "adjudicator_id" bigint not null default (current_setting('jwt.claims.user_id'::text))::bigint,
    "adjudicator_role" adjudicator_role not null default 'adjudicator'::adjudicator_role,
    "rank" integer not null
);


alter table "public"."team_scores" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "type" team_type not null default 'active'::team_type,
    "search_index" text generated always as (create_search(lower(name))) stored
);


alter table "public"."teams" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid default auth.uid(),
    "name" text not null,
    "surname" text not null,
    "search_index" text generated always as (create_search(lower((name || surname)))) stored
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX adjudicator_assignments_debate_id_user_id_key ON public.adjudicator_assignments USING btree (debate_id, user_id);

CREATE UNIQUE INDEX adjudicator_assignments_pkey ON public.adjudicator_assignments USING btree (id);

CREATE UNIQUE INDEX awards_pkey ON public.awards USING btree (id);

CREATE UNIQUE INDEX awards_user_id_award_level_key ON public.awards USING btree (user_id, award, level);

CREATE UNIQUE INDEX claims_pkey ON public.claims USING btree (id);

CREATE UNIQUE INDEX claims_user_id_key ON public.claims USING btree (user_id);

CREATE UNIQUE INDEX club_managers_club_id_user_id_key ON public.club_managers USING btree (club_id, user_id);

CREATE UNIQUE INDEX club_managers_pkey ON public.club_managers USING btree (id);

CREATE UNIQUE INDEX clubs_name_league_key ON public.clubs USING btree (name, league);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX debater_scores_pkey ON public.debater_scores USING btree (id);

CREATE UNIQUE INDEX debates_pkey ON public.debates USING btree (id);

CREATE UNIQUE INDEX debates_round_id_room_key ON public.debates USING btree (round_id, room);

CREATE UNIQUE INDEX details_pkey ON public.details USING btree (id);

CREATE UNIQUE INDEX details_user_id_key ON public.details USING btree (user_id);

CREATE UNIQUE INDEX event_organizers_event_id_user_id_key ON public.event_organizers USING btree (event_id, user_id);

CREATE UNIQUE INDEX event_organizers_pkey ON public.event_organizers USING btree (id);

CREATE UNIQUE INDEX event_registrations_event_id_user_id_key ON public.event_registrations USING btree (event_id, user_id);

CREATE UNIQUE INDEX event_registrations_pkey ON public.event_registrations USING btree (id);

CREATE UNIQUE INDEX events_code_key ON public.events USING btree (code);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX invoices_pkey ON public.invoices USING btree (id);

CREATE INDEX ix_adjudicator_assignments_debate_id ON public.adjudicator_assignments USING btree (debate_id);

CREATE INDEX ix_adjudicator_assignments_user_id ON public.adjudicator_assignments USING btree (user_id);

CREATE INDEX ix_awards_user_id ON public.awards USING btree (user_id);

CREATE INDEX ix_claims_role ON public.claims USING btree (role);

CREATE INDEX ix_club_managers_club_id ON public.club_managers USING btree (club_id);

CREATE INDEX ix_club_managers_user_id ON public.club_managers USING btree (user_id);

CREATE INDEX ix_clubs_active ON public.clubs USING btree (active);

CREATE INDEX ix_clubs_search_index ON public.clubs USING btree (search_index);

CREATE INDEX ix_debater_scores_team_score_id ON public.debater_scores USING btree (team_score_id);

CREATE INDEX ix_debater_scores_user_id ON public.debater_scores USING btree (user_id);

CREATE INDEX ix_debates_round_id ON public.debates USING btree (round_id);

CREATE INDEX ix_event_organizers_event_id ON public.event_organizers USING btree (event_id);

CREATE INDEX ix_event_organizers_user_id ON public.event_organizers USING btree (user_id);

CREATE INDEX ix_event_registrations_event_id ON public.event_registrations USING btree (event_id);

CREATE INDEX ix_event_registrations_user_id ON public.event_registrations USING btree (user_id);

CREATE INDEX ix_events_code ON public.events USING btree (code);

CREATE INDEX ix_events_draft ON public.events USING btree (draft);

CREATE INDEX ix_events_search_index ON public.events USING btree (search_index);

CREATE INDEX ix_events_status ON public.events USING btree (status);

CREATE INDEX ix_invoices_status ON public.invoices USING btree (status);

CREATE INDEX ix_invoices_user_id ON public.invoices USING btree (user_id);

CREATE INDEX ix_memberships_club_id ON public.memberships USING btree (club_id);

CREATE INDEX ix_memberships_confirmed ON public.memberships USING btree (confirmed);

CREATE INDEX ix_memberships_user_id ON public.memberships USING btree (user_id);

CREATE INDEX ix_messages_platform ON public.messages USING btree (platform);

CREATE INDEX ix_messages_type ON public.messages USING btree (type);

CREATE INDEX ix_payments_created_at ON public.payments USING btree (created_at);

CREATE INDEX ix_payments_invoice_id ON public.payments USING btree (invoice_id);

CREATE INDEX ix_payments_user_id ON public.payments USING btree (user_id);

CREATE INDEX ix_rounds_event_id ON public.rounds USING btree (event_id);

CREATE INDEX ix_rounds_motion_id ON public.rounds USING btree (motion_id);

CREATE INDEX ix_supplementary_speeches_team_score_id ON public.supplementary_speeches USING btree (team_score_id);

CREATE INDEX ix_team_assignments_debate_id ON public.team_assignments USING btree (debate_id);

CREATE INDEX ix_team_assignments_team_id ON public.team_assignments USING btree (team_id);

CREATE INDEX ix_team_memberships_event_id ON public.team_memberships USING btree (event_id);

CREATE INDEX ix_team_memberships_team_id ON public.team_memberships USING btree (team_id);

CREATE INDEX ix_team_memberships_user_id ON public.team_memberships USING btree (user_id);

CREATE INDEX ix_team_scores_adjudicator_id ON public.team_scores USING btree (adjudicator_id);

CREATE INDEX ix_team_scores_debate_id ON public.team_scores USING btree (debate_id);

CREATE INDEX ix_team_scores_team_id ON public.team_scores USING btree (team_id);

CREATE INDEX ix_teams_search_index ON public.teams USING btree (search_index);

CREATE INDEX ix_teams_type ON public.teams USING btree (type);

CREATE INDEX ix_users_auth_id ON public.users USING btree (auth_id);

CREATE INDEX ix_users_search_index ON public.users USING btree (search_index);

CREATE UNIQUE INDEX memberships_pkey ON public.memberships USING btree (id);

CREATE UNIQUE INDEX memberships_user_id_club_id_year_key ON public.memberships USING btree (user_id, club_id, year);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX motions_pkey ON public.motions USING btree (id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

CREATE UNIQUE INDEX payments_user_id_key ON public.payments USING btree (user_id);

CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);

CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);

CREATE UNIQUE INDEX rounds_event_id_name_key ON public.rounds USING btree (event_id, name);

CREATE UNIQUE INDEX rounds_pkey ON public.rounds USING btree (id);

CREATE UNIQUE INDEX supervisors_pkey ON public.supervisors USING btree (id);

CREATE UNIQUE INDEX supervisors_user_id_key ON public.supervisors USING btree (user_id);

CREATE UNIQUE INDEX supplementary_speeches_pkey ON public.supplementary_speeches USING btree (id);

CREATE UNIQUE INDEX team_assignments_debate_id_team_id_key ON public.team_assignments USING btree (debate_id, team_id);

CREATE UNIQUE INDEX team_assignments_pkey ON public.team_assignments USING btree (id);

CREATE UNIQUE INDEX team_memberships_pkey ON public.team_memberships USING btree (id);

CREATE UNIQUE INDEX team_memberships_team_id_user_id_event_id_key ON public.team_memberships USING btree (team_id, user_id, event_id);

CREATE UNIQUE INDEX team_scores_debate_id_team_id_adjudicator_id_key ON public.team_scores USING btree (debate_id, team_id, adjudicator_id);

CREATE UNIQUE INDEX team_scores_pkey ON public.team_scores USING btree (id);

CREATE UNIQUE INDEX teams_name_key ON public.teams USING btree (name);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."adjudicator_assignments" add constraint "adjudicator_assignments_pkey" PRIMARY KEY using index "adjudicator_assignments_pkey";

alter table "public"."awards" add constraint "awards_pkey" PRIMARY KEY using index "awards_pkey";

alter table "public"."claims" add constraint "claims_pkey" PRIMARY KEY using index "claims_pkey";

alter table "public"."club_managers" add constraint "club_managers_pkey" PRIMARY KEY using index "club_managers_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."debater_scores" add constraint "debater_scores_pkey" PRIMARY KEY using index "debater_scores_pkey";

alter table "public"."debates" add constraint "debates_pkey" PRIMARY KEY using index "debates_pkey";

alter table "public"."details" add constraint "details_pkey" PRIMARY KEY using index "details_pkey";

alter table "public"."event_organizers" add constraint "event_organizers_pkey" PRIMARY KEY using index "event_organizers_pkey";

alter table "public"."event_registrations" add constraint "event_registrations_pkey" PRIMARY KEY using index "event_registrations_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."invoices" add constraint "invoices_pkey" PRIMARY KEY using index "invoices_pkey";

alter table "public"."memberships" add constraint "memberships_pkey" PRIMARY KEY using index "memberships_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."motions" add constraint "motions_pkey" PRIMARY KEY using index "motions_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";

alter table "public"."rounds" add constraint "rounds_pkey" PRIMARY KEY using index "rounds_pkey";

alter table "public"."supervisors" add constraint "supervisors_pkey" PRIMARY KEY using index "supervisors_pkey";

alter table "public"."supplementary_speeches" add constraint "supplementary_speeches_pkey" PRIMARY KEY using index "supplementary_speeches_pkey";

alter table "public"."team_assignments" add constraint "team_assignments_pkey" PRIMARY KEY using index "team_assignments_pkey";

alter table "public"."team_memberships" add constraint "team_memberships_pkey" PRIMARY KEY using index "team_memberships_pkey";

alter table "public"."team_scores" add constraint "team_scores_pkey" PRIMARY KEY using index "team_scores_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."adjudicator_assignments" add constraint "adjudicator_assignments_debate_id_fkey" FOREIGN KEY (debate_id) REFERENCES debates(id) ON DELETE CASCADE not valid;

alter table "public"."adjudicator_assignments" validate constraint "adjudicator_assignments_debate_id_fkey";

alter table "public"."adjudicator_assignments" add constraint "adjudicator_assignments_debate_id_user_id_key" UNIQUE using index "adjudicator_assignments_debate_id_user_id_key";

alter table "public"."adjudicator_assignments" add constraint "adjudicator_assignments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."adjudicator_assignments" validate constraint "adjudicator_assignments_user_id_fkey";

alter table "public"."awards" add constraint "awards_awarded_by_fkey" FOREIGN KEY (awarded_by) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "public"."awards" validate constraint "awards_awarded_by_fkey";

alter table "public"."awards" add constraint "awards_user_id_award_level_key" UNIQUE using index "awards_user_id_award_level_key";

alter table "public"."awards" add constraint "awards_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."awards" validate constraint "awards_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."claims" validate constraint "claims_user_id_fkey";

alter table "public"."claims" add constraint "claims_user_id_key" UNIQUE using index "claims_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_club_id_fkey";

alter table "public"."club_managers" add constraint "club_managers_club_id_user_id_key" UNIQUE using index "club_managers_club_id_user_id_key";

alter table "public"."club_managers" add constraint "club_managers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."club_managers" validate constraint "club_managers_user_id_fkey";

alter table "public"."clubs" add constraint "clubs_name_league_key" UNIQUE using index "clubs_name_league_key";

alter table "public"."debater_scores" add constraint "debater_scores_team_score_id_fkey" FOREIGN KEY (team_score_id) REFERENCES team_scores(id) ON DELETE CASCADE not valid;

alter table "public"."debater_scores" validate constraint "debater_scores_team_score_id_fkey";

alter table "public"."debater_scores" add constraint "debater_scores_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."debater_scores" validate constraint "debater_scores_user_id_fkey";

alter table "public"."debates" add constraint "debates_round_id_fkey" FOREIGN KEY (round_id) REFERENCES rounds(id) ON DELETE CASCADE not valid;

alter table "public"."debates" validate constraint "debates_round_id_fkey";

alter table "public"."debates" add constraint "debates_round_id_room_key" UNIQUE using index "debates_round_id_room_key";

alter table "public"."details" add constraint "details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."details" validate constraint "details_user_id_fkey";

alter table "public"."details" add constraint "details_user_id_key" UNIQUE using index "details_user_id_key";

alter table "public"."event_organizers" add constraint "event_organizers_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."event_organizers" validate constraint "event_organizers_event_id_fkey";

alter table "public"."event_organizers" add constraint "event_organizers_event_id_user_id_key" UNIQUE using index "event_organizers_event_id_user_id_key";

alter table "public"."event_organizers" add constraint "event_organizers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."event_organizers" validate constraint "event_organizers_user_id_fkey";

alter table "public"."event_registrations" add constraint "event_registrations_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."event_registrations" validate constraint "event_registrations_event_id_fkey";

alter table "public"."event_registrations" add constraint "event_registrations_event_id_user_id_key" UNIQUE using index "event_registrations_event_id_user_id_key";

alter table "public"."event_registrations" add constraint "event_registrations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."event_registrations" validate constraint "event_registrations_user_id_fkey";

alter table "public"."events" add constraint "events_code_key" UNIQUE using index "events_code_key";

alter table "public"."invoices" add constraint "invoices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."invoices" validate constraint "invoices_user_id_fkey";

alter table "public"."memberships" add constraint "memberships_club_id_fkey" FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE not valid;

alter table "public"."memberships" validate constraint "memberships_club_id_fkey";

alter table "public"."memberships" add constraint "memberships_user_id_club_id_year_key" UNIQUE using index "memberships_user_id_club_id_year_key";

alter table "public"."memberships" add constraint "memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."memberships" validate constraint "memberships_user_id_fkey";

alter table "public"."motions" add constraint "motions_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."motions" validate constraint "motions_event_id_fkey";

alter table "public"."payments" add constraint "payments_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL not valid;

alter table "public"."payments" validate constraint "payments_invoice_id_fkey";

alter table "public"."payments" add constraint "payments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_user_id_fkey";

alter table "public"."payments" add constraint "payments_user_id_key" UNIQUE using index "payments_user_id_key";

alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";

alter table "public"."rounds" add constraint "rounds_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."rounds" validate constraint "rounds_event_id_fkey";

alter table "public"."rounds" add constraint "rounds_event_id_name_key" UNIQUE using index "rounds_event_id_name_key";

alter table "public"."rounds" add constraint "rounds_motion_id_fkey" FOREIGN KEY (motion_id) REFERENCES motions(id) ON DELETE SET NULL not valid;

alter table "public"."rounds" validate constraint "rounds_motion_id_fkey";

alter table "public"."supervisors" add constraint "supervisors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."supervisors" validate constraint "supervisors_user_id_fkey";

alter table "public"."supervisors" add constraint "supervisors_user_id_key" UNIQUE using index "supervisors_user_id_key";

alter table "public"."supplementary_speeches" add constraint "supplementary_speeches_team_score_id_fkey" FOREIGN KEY (team_score_id) REFERENCES team_scores(id) ON DELETE CASCADE not valid;

alter table "public"."supplementary_speeches" validate constraint "supplementary_speeches_team_score_id_fkey";

alter table "public"."team_assignments" add constraint "team_assignments_debate_id_fkey" FOREIGN KEY (debate_id) REFERENCES debates(id) ON DELETE CASCADE not valid;

alter table "public"."team_assignments" validate constraint "team_assignments_debate_id_fkey";

alter table "public"."team_assignments" add constraint "team_assignments_debate_id_team_id_key" UNIQUE using index "team_assignments_debate_id_team_id_key";

alter table "public"."team_assignments" add constraint "team_assignments_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."team_assignments" validate constraint "team_assignments_team_id_fkey";

alter table "public"."team_memberships" add constraint "team_memberships_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE not valid;

alter table "public"."team_memberships" validate constraint "team_memberships_event_id_fkey";

alter table "public"."team_memberships" add constraint "team_memberships_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."team_memberships" validate constraint "team_memberships_team_id_fkey";

alter table "public"."team_memberships" add constraint "team_memberships_team_id_user_id_event_id_key" UNIQUE using index "team_memberships_team_id_user_id_event_id_key";

alter table "public"."team_memberships" add constraint "team_memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."team_memberships" validate constraint "team_memberships_user_id_fkey";

alter table "public"."team_scores" add constraint "team_scores_adjudicator_id_fkey" FOREIGN KEY (adjudicator_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."team_scores" validate constraint "team_scores_adjudicator_id_fkey";

alter table "public"."team_scores" add constraint "team_scores_debate_id_fkey" FOREIGN KEY (debate_id) REFERENCES debates(id) ON DELETE CASCADE not valid;

alter table "public"."team_scores" validate constraint "team_scores_debate_id_fkey";

alter table "public"."team_scores" add constraint "team_scores_debate_id_team_id_adjudicator_id_key" UNIQUE using index "team_scores_debate_id_team_id_adjudicator_id_key";

alter table "public"."team_scores" add constraint "team_scores_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."team_scores" validate constraint "team_scores_team_id_fkey";

alter table "public"."teams" add constraint "teams_name_key" UNIQUE using index "teams_name_key";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_auth_id_key" UNIQUE using index "users_auth_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  bind_permissions int;
  current_user_role public.app_role;
begin
  -- Retrieves the 'user_role' claim from the current user's JWT.
  -- This will be NULL if the claim is not set or is JSON null.
  select ((select auth.jwt()) ->> 'user_role')::public.app_role into current_user_role;

  -- If current_user_role is NULL (e.g., claim missing, or was explicitly set to null),
  -- then the user has no specific role for permission checking.
  if current_user_role is null then
    return false;
  end if;

  -- Checks if the user's role has the requested permission in the 'role_permissions' table.
  select count(*)
  into bind_permissions
  from public.role_permissions
  where public.role_permissions.permission = requested_permission
    and public.role_permissions.role = current_user_role;
  return bind_permissions > 0;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  claims jsonb;
  user_role public.app_role;
  user_credential smallint;
  user_additional jsonb;
  db_user_id bigint;
begin
  -- Initialize claims to the existing claims object from the event
  claims := event->'claims';

  -- Fetch the user's role, credentials, additional data, and db user id
  select c.role, c.credential, c.additional, u.id
    into user_role, user_credential, user_additional, db_user_id
    from public.claims as c
    join public.users as u on c.user_id = u.id
    where u.auth_id = (event->>'user_id')::uuid;

  -- Check if user data was found
  if db_user_id is null then
    raise notice 'User not found for auth_id: %', event->>'user_id';
    -- Return the original event instead of an error
    return event;
  end if;

  -- Append the user-specific claims to the existing claims object
  claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  claims := jsonb_set(claims, '{user_credential}', to_jsonb(coalesce(user_credential, null)));
  claims := jsonb_set(claims, '{user_additional}', coalesce(user_additional, '{}'::jsonb));
  claims := jsonb_set(claims, '{user_id}', to_jsonb(db_user_id));

  -- Update the 'claims' object in the original event
  event := jsonb_set(event, '{claims}', claims);

  return event;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.claims (user_id, role, credential)
  values (new.id, 'user', 0);
  insert into public.details (user_id)
  values (new.id);
  return new;
end;
$function$
;

grant delete on table "public"."adjudicator_assignments" to "anon";

grant insert on table "public"."adjudicator_assignments" to "anon";

grant references on table "public"."adjudicator_assignments" to "anon";

grant select on table "public"."adjudicator_assignments" to "anon";

grant trigger on table "public"."adjudicator_assignments" to "anon";

grant truncate on table "public"."adjudicator_assignments" to "anon";

grant update on table "public"."adjudicator_assignments" to "anon";

grant delete on table "public"."adjudicator_assignments" to "authenticated";

grant insert on table "public"."adjudicator_assignments" to "authenticated";

grant references on table "public"."adjudicator_assignments" to "authenticated";

grant select on table "public"."adjudicator_assignments" to "authenticated";

grant trigger on table "public"."adjudicator_assignments" to "authenticated";

grant truncate on table "public"."adjudicator_assignments" to "authenticated";

grant update on table "public"."adjudicator_assignments" to "authenticated";

grant delete on table "public"."adjudicator_assignments" to "service_role";

grant insert on table "public"."adjudicator_assignments" to "service_role";

grant references on table "public"."adjudicator_assignments" to "service_role";

grant select on table "public"."adjudicator_assignments" to "service_role";

grant trigger on table "public"."adjudicator_assignments" to "service_role";

grant truncate on table "public"."adjudicator_assignments" to "service_role";

grant update on table "public"."adjudicator_assignments" to "service_role";

grant delete on table "public"."awards" to "anon";

grant insert on table "public"."awards" to "anon";

grant references on table "public"."awards" to "anon";

grant select on table "public"."awards" to "anon";

grant trigger on table "public"."awards" to "anon";

grant truncate on table "public"."awards" to "anon";

grant update on table "public"."awards" to "anon";

grant delete on table "public"."awards" to "authenticated";

grant insert on table "public"."awards" to "authenticated";

grant references on table "public"."awards" to "authenticated";

grant select on table "public"."awards" to "authenticated";

grant trigger on table "public"."awards" to "authenticated";

grant truncate on table "public"."awards" to "authenticated";

grant update on table "public"."awards" to "authenticated";

grant delete on table "public"."awards" to "service_role";

grant insert on table "public"."awards" to "service_role";

grant references on table "public"."awards" to "service_role";

grant select on table "public"."awards" to "service_role";

grant trigger on table "public"."awards" to "service_role";

grant truncate on table "public"."awards" to "service_role";

grant update on table "public"."awards" to "service_role";

grant delete on table "public"."claims" to "anon";

grant insert on table "public"."claims" to "anon";

grant references on table "public"."claims" to "anon";

grant select on table "public"."claims" to "anon";

grant trigger on table "public"."claims" to "anon";

grant truncate on table "public"."claims" to "anon";

grant update on table "public"."claims" to "anon";

grant delete on table "public"."claims" to "authenticated";

grant insert on table "public"."claims" to "authenticated";

grant references on table "public"."claims" to "authenticated";

grant select on table "public"."claims" to "authenticated";

grant trigger on table "public"."claims" to "authenticated";

grant truncate on table "public"."claims" to "authenticated";

grant update on table "public"."claims" to "authenticated";

grant delete on table "public"."claims" to "service_role";

grant insert on table "public"."claims" to "service_role";

grant references on table "public"."claims" to "service_role";

grant select on table "public"."claims" to "service_role";

grant trigger on table "public"."claims" to "service_role";

grant truncate on table "public"."claims" to "service_role";

grant update on table "public"."claims" to "service_role";

grant delete on table "public"."club_managers" to "anon";

grant insert on table "public"."club_managers" to "anon";

grant references on table "public"."club_managers" to "anon";

grant select on table "public"."club_managers" to "anon";

grant trigger on table "public"."club_managers" to "anon";

grant truncate on table "public"."club_managers" to "anon";

grant update on table "public"."club_managers" to "anon";

grant delete on table "public"."club_managers" to "authenticated";

grant insert on table "public"."club_managers" to "authenticated";

grant references on table "public"."club_managers" to "authenticated";

grant select on table "public"."club_managers" to "authenticated";

grant trigger on table "public"."club_managers" to "authenticated";

grant truncate on table "public"."club_managers" to "authenticated";

grant update on table "public"."club_managers" to "authenticated";

grant delete on table "public"."club_managers" to "service_role";

grant insert on table "public"."club_managers" to "service_role";

grant references on table "public"."club_managers" to "service_role";

grant select on table "public"."club_managers" to "service_role";

grant trigger on table "public"."club_managers" to "service_role";

grant truncate on table "public"."club_managers" to "service_role";

grant update on table "public"."club_managers" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."debater_scores" to "anon";

grant insert on table "public"."debater_scores" to "anon";

grant references on table "public"."debater_scores" to "anon";

grant select on table "public"."debater_scores" to "anon";

grant trigger on table "public"."debater_scores" to "anon";

grant truncate on table "public"."debater_scores" to "anon";

grant update on table "public"."debater_scores" to "anon";

grant delete on table "public"."debater_scores" to "authenticated";

grant insert on table "public"."debater_scores" to "authenticated";

grant references on table "public"."debater_scores" to "authenticated";

grant select on table "public"."debater_scores" to "authenticated";

grant trigger on table "public"."debater_scores" to "authenticated";

grant truncate on table "public"."debater_scores" to "authenticated";

grant update on table "public"."debater_scores" to "authenticated";

grant delete on table "public"."debater_scores" to "service_role";

grant insert on table "public"."debater_scores" to "service_role";

grant references on table "public"."debater_scores" to "service_role";

grant select on table "public"."debater_scores" to "service_role";

grant trigger on table "public"."debater_scores" to "service_role";

grant truncate on table "public"."debater_scores" to "service_role";

grant update on table "public"."debater_scores" to "service_role";

grant delete on table "public"."debates" to "anon";

grant insert on table "public"."debates" to "anon";

grant references on table "public"."debates" to "anon";

grant select on table "public"."debates" to "anon";

grant trigger on table "public"."debates" to "anon";

grant truncate on table "public"."debates" to "anon";

grant update on table "public"."debates" to "anon";

grant delete on table "public"."debates" to "authenticated";

grant insert on table "public"."debates" to "authenticated";

grant references on table "public"."debates" to "authenticated";

grant select on table "public"."debates" to "authenticated";

grant trigger on table "public"."debates" to "authenticated";

grant truncate on table "public"."debates" to "authenticated";

grant update on table "public"."debates" to "authenticated";

grant delete on table "public"."debates" to "service_role";

grant insert on table "public"."debates" to "service_role";

grant references on table "public"."debates" to "service_role";

grant select on table "public"."debates" to "service_role";

grant trigger on table "public"."debates" to "service_role";

grant truncate on table "public"."debates" to "service_role";

grant update on table "public"."debates" to "service_role";

grant delete on table "public"."details" to "anon";

grant insert on table "public"."details" to "anon";

grant references on table "public"."details" to "anon";

grant select on table "public"."details" to "anon";

grant trigger on table "public"."details" to "anon";

grant truncate on table "public"."details" to "anon";

grant update on table "public"."details" to "anon";

grant delete on table "public"."details" to "authenticated";

grant insert on table "public"."details" to "authenticated";

grant references on table "public"."details" to "authenticated";

grant select on table "public"."details" to "authenticated";

grant trigger on table "public"."details" to "authenticated";

grant truncate on table "public"."details" to "authenticated";

grant update on table "public"."details" to "authenticated";

grant delete on table "public"."details" to "service_role";

grant insert on table "public"."details" to "service_role";

grant references on table "public"."details" to "service_role";

grant select on table "public"."details" to "service_role";

grant trigger on table "public"."details" to "service_role";

grant truncate on table "public"."details" to "service_role";

grant update on table "public"."details" to "service_role";

grant delete on table "public"."event_organizers" to "anon";

grant insert on table "public"."event_organizers" to "anon";

grant references on table "public"."event_organizers" to "anon";

grant select on table "public"."event_organizers" to "anon";

grant trigger on table "public"."event_organizers" to "anon";

grant truncate on table "public"."event_organizers" to "anon";

grant update on table "public"."event_organizers" to "anon";

grant delete on table "public"."event_organizers" to "authenticated";

grant insert on table "public"."event_organizers" to "authenticated";

grant references on table "public"."event_organizers" to "authenticated";

grant select on table "public"."event_organizers" to "authenticated";

grant trigger on table "public"."event_organizers" to "authenticated";

grant truncate on table "public"."event_organizers" to "authenticated";

grant update on table "public"."event_organizers" to "authenticated";

grant delete on table "public"."event_organizers" to "service_role";

grant insert on table "public"."event_organizers" to "service_role";

grant references on table "public"."event_organizers" to "service_role";

grant select on table "public"."event_organizers" to "service_role";

grant trigger on table "public"."event_organizers" to "service_role";

grant truncate on table "public"."event_organizers" to "service_role";

grant update on table "public"."event_organizers" to "service_role";

grant delete on table "public"."event_registrations" to "anon";

grant insert on table "public"."event_registrations" to "anon";

grant references on table "public"."event_registrations" to "anon";

grant select on table "public"."event_registrations" to "anon";

grant trigger on table "public"."event_registrations" to "anon";

grant truncate on table "public"."event_registrations" to "anon";

grant update on table "public"."event_registrations" to "anon";

grant delete on table "public"."event_registrations" to "authenticated";

grant insert on table "public"."event_registrations" to "authenticated";

grant references on table "public"."event_registrations" to "authenticated";

grant select on table "public"."event_registrations" to "authenticated";

grant trigger on table "public"."event_registrations" to "authenticated";

grant truncate on table "public"."event_registrations" to "authenticated";

grant update on table "public"."event_registrations" to "authenticated";

grant delete on table "public"."event_registrations" to "service_role";

grant insert on table "public"."event_registrations" to "service_role";

grant references on table "public"."event_registrations" to "service_role";

grant select on table "public"."event_registrations" to "service_role";

grant trigger on table "public"."event_registrations" to "service_role";

grant truncate on table "public"."event_registrations" to "service_role";

grant update on table "public"."event_registrations" to "service_role";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."invoices" to "anon";

grant insert on table "public"."invoices" to "anon";

grant references on table "public"."invoices" to "anon";

grant select on table "public"."invoices" to "anon";

grant trigger on table "public"."invoices" to "anon";

grant truncate on table "public"."invoices" to "anon";

grant update on table "public"."invoices" to "anon";

grant delete on table "public"."invoices" to "authenticated";

grant insert on table "public"."invoices" to "authenticated";

grant references on table "public"."invoices" to "authenticated";

grant select on table "public"."invoices" to "authenticated";

grant trigger on table "public"."invoices" to "authenticated";

grant truncate on table "public"."invoices" to "authenticated";

grant update on table "public"."invoices" to "authenticated";

grant delete on table "public"."invoices" to "service_role";

grant insert on table "public"."invoices" to "service_role";

grant references on table "public"."invoices" to "service_role";

grant select on table "public"."invoices" to "service_role";

grant trigger on table "public"."invoices" to "service_role";

grant truncate on table "public"."invoices" to "service_role";

grant update on table "public"."invoices" to "service_role";

grant delete on table "public"."memberships" to "anon";

grant insert on table "public"."memberships" to "anon";

grant references on table "public"."memberships" to "anon";

grant select on table "public"."memberships" to "anon";

grant trigger on table "public"."memberships" to "anon";

grant truncate on table "public"."memberships" to "anon";

grant update on table "public"."memberships" to "anon";

grant delete on table "public"."memberships" to "authenticated";

grant insert on table "public"."memberships" to "authenticated";

grant references on table "public"."memberships" to "authenticated";

grant select on table "public"."memberships" to "authenticated";

grant trigger on table "public"."memberships" to "authenticated";

grant truncate on table "public"."memberships" to "authenticated";

grant update on table "public"."memberships" to "authenticated";

grant delete on table "public"."memberships" to "service_role";

grant insert on table "public"."memberships" to "service_role";

grant references on table "public"."memberships" to "service_role";

grant select on table "public"."memberships" to "service_role";

grant trigger on table "public"."memberships" to "service_role";

grant truncate on table "public"."memberships" to "service_role";

grant update on table "public"."memberships" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."motions" to "anon";

grant insert on table "public"."motions" to "anon";

grant references on table "public"."motions" to "anon";

grant select on table "public"."motions" to "anon";

grant trigger on table "public"."motions" to "anon";

grant truncate on table "public"."motions" to "anon";

grant update on table "public"."motions" to "anon";

grant delete on table "public"."motions" to "authenticated";

grant insert on table "public"."motions" to "authenticated";

grant references on table "public"."motions" to "authenticated";

grant select on table "public"."motions" to "authenticated";

grant trigger on table "public"."motions" to "authenticated";

grant truncate on table "public"."motions" to "authenticated";

grant update on table "public"."motions" to "authenticated";

grant delete on table "public"."motions" to "service_role";

grant insert on table "public"."motions" to "service_role";

grant references on table "public"."motions" to "service_role";

grant select on table "public"."motions" to "service_role";

grant trigger on table "public"."motions" to "service_role";

grant truncate on table "public"."motions" to "service_role";

grant update on table "public"."motions" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."role_permissions" to "service_role";

grant insert on table "public"."role_permissions" to "service_role";

grant references on table "public"."role_permissions" to "service_role";

grant select on table "public"."role_permissions" to "service_role";

grant trigger on table "public"."role_permissions" to "service_role";

grant truncate on table "public"."role_permissions" to "service_role";

grant update on table "public"."role_permissions" to "service_role";

grant delete on table "public"."role_permissions" to "supabase_auth_admin";

grant insert on table "public"."role_permissions" to "supabase_auth_admin";

grant references on table "public"."role_permissions" to "supabase_auth_admin";

grant select on table "public"."role_permissions" to "supabase_auth_admin";

grant trigger on table "public"."role_permissions" to "supabase_auth_admin";

grant truncate on table "public"."role_permissions" to "supabase_auth_admin";

grant update on table "public"."role_permissions" to "supabase_auth_admin";

grant delete on table "public"."rounds" to "anon";

grant insert on table "public"."rounds" to "anon";

grant references on table "public"."rounds" to "anon";

grant select on table "public"."rounds" to "anon";

grant trigger on table "public"."rounds" to "anon";

grant truncate on table "public"."rounds" to "anon";

grant update on table "public"."rounds" to "anon";

grant delete on table "public"."rounds" to "authenticated";

grant insert on table "public"."rounds" to "authenticated";

grant references on table "public"."rounds" to "authenticated";

grant select on table "public"."rounds" to "authenticated";

grant trigger on table "public"."rounds" to "authenticated";

grant truncate on table "public"."rounds" to "authenticated";

grant update on table "public"."rounds" to "authenticated";

grant delete on table "public"."rounds" to "service_role";

grant insert on table "public"."rounds" to "service_role";

grant references on table "public"."rounds" to "service_role";

grant select on table "public"."rounds" to "service_role";

grant trigger on table "public"."rounds" to "service_role";

grant truncate on table "public"."rounds" to "service_role";

grant update on table "public"."rounds" to "service_role";

grant delete on table "public"."supervisors" to "anon";

grant insert on table "public"."supervisors" to "anon";

grant references on table "public"."supervisors" to "anon";

grant select on table "public"."supervisors" to "anon";

grant trigger on table "public"."supervisors" to "anon";

grant truncate on table "public"."supervisors" to "anon";

grant update on table "public"."supervisors" to "anon";

grant delete on table "public"."supervisors" to "authenticated";

grant insert on table "public"."supervisors" to "authenticated";

grant references on table "public"."supervisors" to "authenticated";

grant select on table "public"."supervisors" to "authenticated";

grant trigger on table "public"."supervisors" to "authenticated";

grant truncate on table "public"."supervisors" to "authenticated";

grant update on table "public"."supervisors" to "authenticated";

grant delete on table "public"."supervisors" to "service_role";

grant insert on table "public"."supervisors" to "service_role";

grant references on table "public"."supervisors" to "service_role";

grant select on table "public"."supervisors" to "service_role";

grant trigger on table "public"."supervisors" to "service_role";

grant truncate on table "public"."supervisors" to "service_role";

grant update on table "public"."supervisors" to "service_role";

grant delete on table "public"."supplementary_speeches" to "anon";

grant insert on table "public"."supplementary_speeches" to "anon";

grant references on table "public"."supplementary_speeches" to "anon";

grant select on table "public"."supplementary_speeches" to "anon";

grant trigger on table "public"."supplementary_speeches" to "anon";

grant truncate on table "public"."supplementary_speeches" to "anon";

grant update on table "public"."supplementary_speeches" to "anon";

grant delete on table "public"."supplementary_speeches" to "authenticated";

grant insert on table "public"."supplementary_speeches" to "authenticated";

grant references on table "public"."supplementary_speeches" to "authenticated";

grant select on table "public"."supplementary_speeches" to "authenticated";

grant trigger on table "public"."supplementary_speeches" to "authenticated";

grant truncate on table "public"."supplementary_speeches" to "authenticated";

grant update on table "public"."supplementary_speeches" to "authenticated";

grant delete on table "public"."supplementary_speeches" to "service_role";

grant insert on table "public"."supplementary_speeches" to "service_role";

grant references on table "public"."supplementary_speeches" to "service_role";

grant select on table "public"."supplementary_speeches" to "service_role";

grant trigger on table "public"."supplementary_speeches" to "service_role";

grant truncate on table "public"."supplementary_speeches" to "service_role";

grant update on table "public"."supplementary_speeches" to "service_role";

grant delete on table "public"."team_assignments" to "anon";

grant insert on table "public"."team_assignments" to "anon";

grant references on table "public"."team_assignments" to "anon";

grant select on table "public"."team_assignments" to "anon";

grant trigger on table "public"."team_assignments" to "anon";

grant truncate on table "public"."team_assignments" to "anon";

grant update on table "public"."team_assignments" to "anon";

grant delete on table "public"."team_assignments" to "authenticated";

grant insert on table "public"."team_assignments" to "authenticated";

grant references on table "public"."team_assignments" to "authenticated";

grant select on table "public"."team_assignments" to "authenticated";

grant trigger on table "public"."team_assignments" to "authenticated";

grant truncate on table "public"."team_assignments" to "authenticated";

grant update on table "public"."team_assignments" to "authenticated";

grant delete on table "public"."team_assignments" to "service_role";

grant insert on table "public"."team_assignments" to "service_role";

grant references on table "public"."team_assignments" to "service_role";

grant select on table "public"."team_assignments" to "service_role";

grant trigger on table "public"."team_assignments" to "service_role";

grant truncate on table "public"."team_assignments" to "service_role";

grant update on table "public"."team_assignments" to "service_role";

grant delete on table "public"."team_memberships" to "anon";

grant insert on table "public"."team_memberships" to "anon";

grant references on table "public"."team_memberships" to "anon";

grant select on table "public"."team_memberships" to "anon";

grant trigger on table "public"."team_memberships" to "anon";

grant truncate on table "public"."team_memberships" to "anon";

grant update on table "public"."team_memberships" to "anon";

grant delete on table "public"."team_memberships" to "authenticated";

grant insert on table "public"."team_memberships" to "authenticated";

grant references on table "public"."team_memberships" to "authenticated";

grant select on table "public"."team_memberships" to "authenticated";

grant trigger on table "public"."team_memberships" to "authenticated";

grant truncate on table "public"."team_memberships" to "authenticated";

grant update on table "public"."team_memberships" to "authenticated";

grant delete on table "public"."team_memberships" to "service_role";

grant insert on table "public"."team_memberships" to "service_role";

grant references on table "public"."team_memberships" to "service_role";

grant select on table "public"."team_memberships" to "service_role";

grant trigger on table "public"."team_memberships" to "service_role";

grant truncate on table "public"."team_memberships" to "service_role";

grant update on table "public"."team_memberships" to "service_role";

grant delete on table "public"."team_scores" to "anon";

grant insert on table "public"."team_scores" to "anon";

grant references on table "public"."team_scores" to "anon";

grant select on table "public"."team_scores" to "anon";

grant trigger on table "public"."team_scores" to "anon";

grant truncate on table "public"."team_scores" to "anon";

grant update on table "public"."team_scores" to "anon";

grant delete on table "public"."team_scores" to "authenticated";

grant insert on table "public"."team_scores" to "authenticated";

grant references on table "public"."team_scores" to "authenticated";

grant select on table "public"."team_scores" to "authenticated";

grant trigger on table "public"."team_scores" to "authenticated";

grant truncate on table "public"."team_scores" to "authenticated";

grant update on table "public"."team_scores" to "authenticated";

grant delete on table "public"."team_scores" to "service_role";

grant insert on table "public"."team_scores" to "service_role";

grant references on table "public"."team_scores" to "service_role";

grant select on table "public"."team_scores" to "service_role";

grant trigger on table "public"."team_scores" to "service_role";

grant truncate on table "public"."team_scores" to "service_role";

grant update on table "public"."team_scores" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Allow read access to adjudicator assignments"
on "public"."adjudicator_assignments"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM debates
  WHERE ((debates.id = adjudicator_assignments.debate_id) AND (debates.round_id IN ( SELECT rounds.id
           FROM rounds
          WHERE (rounds.status <> 'scheduled'::round_status)))))) OR authorize('results.read'::app_permission)));


create policy "Allow users with results.write to manage adjudicator assignment"
on "public"."adjudicator_assignments"
as permissive
for all
to authenticated
using (authorize('results.write'::app_permission));


create policy "Allow authenticated users to read user awards"
on "public"."awards"
as permissive
for select
to authenticated
using (true);


create policy "Allow user roles to create awards"
on "public"."awards"
as permissive
for insert
to authenticated
with check (authorize('awards.write'::app_permission));


create policy "Allow user roles to delete awards"
on "public"."awards"
as permissive
for delete
to authenticated
using (authorize('awards.write'::app_permission));


create policy "Allow authenticated users to read user claims"
on "public"."claims"
as permissive
for select
to authenticated
using (true);


create policy "Allow authenticated users to read club managers"
on "public"."club_managers"
as permissive
for select
to authenticated
using (true);


create policy "Allow users with club_managers.write to create club managers"
on "public"."club_managers"
as permissive
for insert
to authenticated
with check (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to delete club managers"
on "public"."club_managers"
as permissive
for delete
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Allow users with club_managers.write to update club managers"
on "public"."club_managers"
as permissive
for update
to authenticated
using (authorize('club_managers.write'::app_permission));


create policy "Club managers can add managers to their own clubs"
on "public"."club_managers"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM club_managers club_managers_1
  WHERE ((club_managers_1.club_id = club_managers_1.club_id) AND (club_managers_1.user_id = (( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint)))));


create policy "Allow read access to clubs"
on "public"."clubs"
as permissive
for select
to authenticated
using (((active = true) OR authorize('clubs.read'::app_permission)));


create policy "Allow update access to clubs"
on "public"."clubs"
as permissive
for update
to authenticated
using (((EXISTS ( SELECT 1
   FROM club_managers
  WHERE ((club_managers.club_id = clubs.id) AND (club_managers.user_id = ( SELECT users.id
           FROM users
          WHERE (users.auth_id = ( SELECT auth.uid() AS uid))))))) OR authorize('clubs.write'::app_permission)));


create policy "Allow users with clubs.write to create clubs"
on "public"."clubs"
as permissive
for insert
to authenticated
with check (authorize('clubs.write'::app_permission));


create policy "Allow read access to debater scores"
on "public"."debater_scores"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM (((team_scores ts
     JOIN debates d ON ((d.id = ts.debate_id)))
     JOIN rounds r ON ((r.id = d.round_id)))
     JOIN events e ON ((e.id = r.event_id)))
  WHERE ((ts.id = debater_scores.team_score_id) AND (e.status = 'completed'::event_status)))) OR authorize('results.read'::app_permission)));


create policy "Allow users to manage their own debater scores"
on "public"."debater_scores"
as permissive
for all
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = ( SELECT team_scores.adjudicator_id
   FROM team_scores
  WHERE (team_scores.id = debater_scores.team_score_id))) OR authorize('results.write'::app_permission)));


create policy "Allow read access to debates"
on "public"."debates"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM rounds
  WHERE ((rounds.id = debates.round_id) AND (rounds.status <> 'scheduled'::round_status)))) OR authorize('results.read'::app_permission)));


create policy "Allow users with results.write to manage debates"
on "public"."debates"
as permissive
for all
to authenticated
using (authorize('results.write'::app_permission));


create policy "Allow read access to details"
on "public"."details"
as permissive
for select
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('details.read'::app_permission)));


create policy "Allow update access to details"
on "public"."details"
as permissive
for update
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('details.write'::app_permission)))
with check ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('details.write'::app_permission)));


create policy "Allow read access to event organizers"
on "public"."event_organizers"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM events
  WHERE ((events.id = event_organizers.event_id) AND ((events.draft = false) OR authorize('events.read'::app_permission))))) OR authorize('events.read'::app_permission)));


create policy "Allow users with events.write to manage event organizers"
on "public"."event_organizers"
as permissive
for all
to authenticated
using (authorize('events.write'::app_permission));


create policy "Allow users to manage their own event registrations"
on "public"."event_registrations"
as permissive
for all
to authenticated
using (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow users with events.read to read event registrations"
on "public"."event_registrations"
as permissive
for select
to authenticated
using (authorize('events.read'::app_permission));


create policy "Allow users with events.write to manage event registrations"
on "public"."event_registrations"
as permissive
for all
to authenticated
using (authorize('events.write'::app_permission));


create policy "Allow read access to events"
on "public"."events"
as permissive
for select
to authenticated
using (((draft = false) OR authorize('events.read'::app_permission)));


create policy "Allow users with events.write to create events"
on "public"."events"
as permissive
for insert
to authenticated
with check (authorize('events.write'::app_permission));


create policy "Allow users with events.write to update events"
on "public"."events"
as permissive
for update
to authenticated
using (authorize('events.write'::app_permission));


create policy "Allow read access to invoices"
on "public"."invoices"
as permissive
for select
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('invoices.read'::app_permission)));


create policy "Allow users with invoices.write to update invoices"
on "public"."invoices"
as permissive
for update
to authenticated
using (authorize('invoices.write'::app_permission));


create policy "Allow authenticated users to read memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using (true);


create policy "Allow user roles to read memberships"
on "public"."memberships"
as permissive
for select
to authenticated
using (authorize('memberships.read'::app_permission));


create policy "Allow user roles to update memberships"
on "public"."memberships"
as permissive
for update
to authenticated
using (authorize('memberships.write'::app_permission))
with check (authorize('memberships.write'::app_permission));


create policy "Allow users to create their own memberships"
on "public"."memberships"
as permissive
for insert
to authenticated
with check (((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id));


create policy "Allow authenticated users to read messages"
on "public"."messages"
as permissive
for select
to authenticated
using (true);


create policy "Allow users with messages.write to manage messages"
on "public"."messages"
as permissive
for all
to authenticated
using (authorize('messages.write'::app_permission))
with check (authorize('messages.write'::app_permission));


create policy "Allow read access to motions"
on "public"."motions"
as permissive
for select
to authenticated
using (((motion_type = 'prepared'::motion_type) OR (EXISTS ( SELECT 1
   FROM rounds
  WHERE ((rounds.motion_id = motions.id) AND (rounds.status <> 'scheduled'::round_status)))) OR authorize('motions.read'::app_permission)));


create policy "Allow users with motions.write to create motions"
on "public"."motions"
as permissive
for insert
to authenticated
with check (authorize('motions.write'::app_permission));


create policy "Allow users with motions.write to update motions"
on "public"."motions"
as permissive
for update
to authenticated
using (authorize('motions.write'::app_permission));


create policy "Allow read access to payments"
on "public"."payments"
as permissive
for select
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('payments.read'::app_permission)));


create policy "Allow users with payments.delete to delete payments"
on "public"."payments"
as permissive
for delete
to authenticated
using (authorize('payments.write'::app_permission));


create policy "Allow users with payments.read to read payments"
on "public"."payments"
as permissive
for select
to authenticated
using (authorize('payments.read'::app_permission));


create policy "Allow users with payments.write to create payments"
on "public"."payments"
as permissive
for insert
to authenticated
with check (authorize('payments.write'::app_permission));


create policy "Allow users with payments.write to update payments"
on "public"."payments"
as permissive
for update
to authenticated
using (authorize('payments.write'::app_permission));


create policy "Allow auth admin to read role_permissions"
on "public"."role_permissions"
as permissive
for select
to supabase_auth_admin
using (true);


create policy "Allow read access to rounds"
on "public"."rounds"
as permissive
for select
to authenticated
using (((status <> 'scheduled'::round_status) OR authorize('events.read'::app_permission) OR authorize('events.read'::app_permission)));


create policy "Allow users with events.write to create rounds"
on "public"."rounds"
as permissive
for insert
to authenticated
with check (authorize('events.write'::app_permission));


create policy "Allow users with events.write to update rounds"
on "public"."rounds"
as permissive
for update
to authenticated
using (authorize('events.write'::app_permission));


create policy "Allow read access to supervisors"
on "public"."supervisors"
as permissive
for select
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('supervisors.read'::app_permission)));


create policy "Allow update access to supervisors"
on "public"."supervisors"
as permissive
for update
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('supervisors.write'::app_permission)))
with check ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('supervisors.write'::app_permission)));


create policy "Allow user roles to create supervisors"
on "public"."supervisors"
as permissive
for insert
to authenticated
with check (authorize('supervisors.write'::app_permission));


create policy "Allow users to create their own supervisor information"
on "public"."supervisors"
as permissive
for insert
to authenticated
with check ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = user_id) OR authorize('supervisors.write'::app_permission)));


create policy "Allow read access to supplementary speeches"
on "public"."supplementary_speeches"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM (((team_scores ts
     JOIN debates d ON ((d.id = ts.debate_id)))
     JOIN rounds r ON ((r.id = d.round_id)))
     JOIN events e ON ((e.id = r.event_id)))
  WHERE ((ts.id = supplementary_speeches.team_score_id) AND (e.status = 'completed'::event_status)))) OR authorize('results.read'::app_permission)));


create policy "Allow users to manage their own supplementary speeches"
on "public"."supplementary_speeches"
as permissive
for all
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = ( SELECT team_scores.adjudicator_id
   FROM team_scores
  WHERE (team_scores.id = supplementary_speeches.team_score_id))) OR authorize('results.write'::app_permission)));


create policy "Allow read access to team assignments"
on "public"."team_assignments"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM debates
  WHERE ((debates.id = team_assignments.debate_id) AND (debates.round_id IN ( SELECT rounds.id
           FROM rounds
          WHERE (rounds.status <> 'scheduled'::round_status)))))) OR authorize('results.read'::app_permission)));


create policy "Allow users with results.write to manage team assignments"
on "public"."team_assignments"
as permissive
for all
to authenticated
using (authorize('results.write'::app_permission));


create policy "Allow read access to team memberships"
on "public"."team_memberships"
as permissive
for select
to authenticated
using (true);


create policy "Allow users with teams.write to manage team memberships"
on "public"."team_memberships"
as permissive
for all
to authenticated
using (authorize('teams.write'::app_permission));


create policy "Allow read access to team scores"
on "public"."team_scores"
as permissive
for select
to authenticated
using (((EXISTS ( SELECT 1
   FROM ((debates d
     JOIN rounds r ON ((r.id = d.round_id)))
     JOIN events e ON ((e.id = r.event_id)))
  WHERE ((d.id = team_scores.debate_id) AND (e.status = 'completed'::event_status)))) OR authorize('results.read'::app_permission)));


create policy "Allow users to manage their own team scores"
on "public"."team_scores"
as permissive
for all
to authenticated
using ((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = adjudicator_id) OR authorize('results.write'::app_permission)));


create policy "Allow read access to teams"
on "public"."teams"
as permissive
for select
to authenticated
using (true);


create policy "Allow users with teams.write to create teams"
on "public"."teams"
as permissive
for insert
to authenticated
with check (authorize('teams.write'::app_permission));


create policy "Allow users with teams.write to update teams"
on "public"."teams"
as permissive
for update
to authenticated
using (authorize('teams.write'::app_permission));


create policy "Allow authenticated users to read user data"
on "public"."users"
as permissive
for select
to authenticated
using (true);


create policy "Allow update access to user data"
on "public"."users"
as permissive
for update
to authenticated
using (((((( SELECT (auth.jwt() ->> 'user_id'::text)))::bigint = id) AND (( SELECT auth.uid() AS uid) = auth_id)) OR authorize('users.write'::app_permission)));


create policy "Allow users to create their own data"
on "public"."users"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = auth_id));


CREATE TRIGGER on_user_created AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();


