name: Check and Test (Web)

on:
  workflow_call:
  push:
    paths:
      - "web/**"
      - "!web/**/*.md"
      - "!web/LICENSE"
      - "!web/.gitignore"
  pull_request:
    paths:
      - "web/**"
      - "!web/**/*.md"
      - "!web/LICENSE"
      - "!web/.gitignore"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup VITE+
        uses: voidzero-dev/setup-vp@v1.17.0
        with:
          node-version: "26"
          cache: true
          cwd: ./web

      - name: Install dependencies
        run: vp install

      - name: Lint and Type check code (VP & Nuxt)
        run: vp run check

      # - name: Run tests
      #   run: vp test
