allowBuilds:
  esbuild: true
  vue-demi: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
overrides:
  vite: "catalog:"
  typescript: "npm:typescript-native-bridge@6.0.3-bridge.11.tsgo.7.0.2"
  "@tiptap/core": "3.30.2"
  "@tiptap/vue-3": "3.30.2"
  "@tiptap/pm": "3.30.2"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
